# 소행성 관측 계획 수립하기

* 이 노트북을 구글 코랩에서 실행하고자 한다면 [파일] - [드라이브에 사본 저장]을 하여 본인의 소유로 만든 후에 코드를 실행하거나 수정할 수 있습니다.

* 이 파일은 실제 수업에 사용하므로 필요에 따라 예고 없이 변경될 수 있습니다.

* If you have any questions or comments on this document, please email me(Kiehyun.Park@gmail.com).

* 이 파일(문서)는 공교육 현장에서 수업시간에 자유롭게 사용할 수 있으나, 다른 목적으로 사용할 시에는 사전에 연락을 주셔서 상의해 주시기 바랍니다.

이 자료는 What's observable로 부터 특정한 날 관측할 수 있는 소행성의 목록을 만드는 과정을 설명합니다.

## 필요한 환경

이 프로젝트를 위해서는 아래의 모듈이 필요합니다.

> numpy, pandas, matplotlib, astroquery, requests, astropy, astropy.units, certifi, version_information

### 구글 코랩에 한글 폰트 설치

matplotlib에서 한글을 사용하기 위해서는 한글 폰트가 필요하다. 구글 코랩에서 현재의 Jupyter notebook을 실행한다면 아래 코드를 실행 한 후 런타임 다시 시작을 해 줘야 한글을 사용할 수 있을 것이다.

In [12]:
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf

### 런타임 다시 시작

위의 셀을 실행한 다음 반드시 다음 과정을 잊지 말자.

* [메뉴]-[런타임]-[런터임 다시 시작]

* [메뉴]-[런타임]-[이전 셀 실행]을 해주어야 한다.

### 한글 폰트 사용

위에서 한글 폰트를 설치하고, 런타임 다시시작을 했다면 구글 코랩에서 폰트 경로를 설정하여 한글 사용이 가능해 진다.

In [13]:
#visualization
import matplotlib as mpl
import matplotlib.pylab as plb
import matplotlib.pyplot as plt

# 브라우저에서 바로 그려지도록
%matplotlib inline

# 그래프에 retina display 적용
%config InlineBackend.figure_format = 'retina'

# Colab 의 한글 폰트 설정
plt.rc('font', family='NanumBarunGothic')

# 유니코드에서  음수 부호설정
mpl.rc('axes', unicode_minus=False)

### 모듈 설치 및 버전 확인

아래 셀을 실행하면 이 노트북을 실행하는데 필요한 모듈을 설치하고 파이썬 및 관련 모듈의 버전을 확인할 수 있다.

In [14]:
import importlib, sys, subprocess
packages = "numpy, pandas, matplotlib, astroquery, requests, astropy, astropy.units, certifi, version_information" # required modules
pkgs = packages.split(", ")
for pkg in pkgs :
    if not importlib.util.find_spec(pkg):
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg, '-q'])
        print(f"**** {pkg} module is now installed.")
    else:
        print(f"******** {pkg} module is already installed.")
%load_ext version_information
import time
now = time.strftime("%Y-%m-%d %H:%M:%S (%Z = GMT%z)")
print(f"This notebook was generated at {now} ")

vv = %version_information {packages}
for i, pkg in enumerate(vv.packages):
    print(f"{i} {pkg[0]:10s} {pkg[1]:s}")

******** numpy module is already installed.
******** pandas module is already installed.
******** matplotlib module is already installed.
******** astroquery module is already installed.
******** requests module is already installed.
******** astropy module is already installed.
******** astropy.units module is already installed.
******** certifi module is already installed.
******** version_information module is already installed.
The version_information extension is already loaded. To reload it, use:
  %reload_ext version_information
This notebook was generated at 2023-12-03 19:40:55 (KST = GMT+0900)
0 Python     3.11.5 64bit [GCC 11.2.0]
1 IPython    8.15.0
2 OS         Linux 5.15.0 89 generic x86_64 with glibc2.31
3 numpy      1.26.0
4 pandas     2.1.1
5 matplotlib 3.8.0
6 astroquery 0.4.6
7 requests   2.31.0
8 astropy    5.3.4
9 astropy.units The 'astropy.units' distribution was not found and is required by the application
10 certifi    2023.07.22
11 version_information 1.0.4

## 날짜와 시간 다루기

### datetime.datetime

Python 내장 모듈인 datetime을 사용하면 날짜와 시각 객체를 다룰 수 있습니다.

#### 표준시와 세계시

In [15]:
from datetime import datetime, timedelta, timezone

dt_kst_now = datetime.now()
print("현재 시각(KST=GMT+9) :", dt_kst_now)

timezone_utc = timezone(timedelta(hours=-9))
dt_utc_now = dt_kst_now.astimezone(timezone_utc)
print("현재 시각(UTC) :", dt_utc_now)

현재 시각(KST=GMT+9) : 2023-12-03 19:40:55.563316
현재 시각(UTC) : 2023-12-03 01:40:55.563316-09:00

#### fits header의 시간 형식

fits header의 시간 형식은 '2023-09-11T20:19:18'의 형태를 띠고 있는데 datetime.strptime을 이용하면 날짜시간 형식을 바로 datetime 객체로 만들 수 있습니다.

이를 세계시로 바꾸려면 timedelta를 이용할 수 있습니다.

In [16]:
start_dt_kst_str = '2023-09-11T20:19:18'
end_dt_kst_str = '2023-12-31T00:00:00'

start_dt_kst = datetime.strptime(start_dt_kst_str, '%Y-%m-%dT%H:%M:%S')
print(start_dt_kst)
print(type(start_dt_kst))

start_dt_utc = start_dt_kst + timedelta(hours=-9)
print(start_dt_utc)
print(type(start_dt_utc))

2023-09-11 20:19:18
<class 'datetime.datetime'>
2023-09-11 11:19:18
<class 'datetime.datetime'>

#### string 형태로 변환하기

datetime 객체를 string으로 바꿀때는 strftime 메쏘들ㄹ 이용하면 됩니다.

In [17]:

start_dt_utc_str = start_dt_utc.strftime('%Y-%m-%dT%H:%M:%S')
print("start_dt_utc_str :", start_dt_utc_str)
print("type(start_dt_utc_str) :", type(start_dt_utc_str))

start_dt_utc_str : 2023-09-11T11:19:18
type(start_dt_utc_str) : <class 'str'>

#### datetime 이용하여 list 생성

아래와 같이 하면, 시작 시각과 끝나는 시각, 그리고 시간 간격을 정해 주고, Python의 datatime 객체를 이용하여 일정 시간 간격의 목록(list)을 만을 수 있다.

In [18]:
from datetime import datetime, timedelta
start_time_text = "2017-01-01"
end_time_text = "2017-06-01"
dt = 1
def datetime_range(start_dt, end_dt, delta):
    '''
        Parameters
        ----------
        start_dt : datetime.datetime
        end_dt : datetime.datetime
        delta : int
    '''
    current = start_dt
    while current < end_dt:
        yield current
        current += delta

dts = [dt.strftime('%Y-%m-%d') for dt in
            datetime_range(datetime.fromisoformat(start_time_text), datetime.fromisoformat(end_time_text),
            timedelta(days=dt))]

print("len(dts):", len(dts))
print("dts", dts)

len(dts): 151
dts ['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08', '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12', '2017-01-13', '2017-01-14', '2017-01-15', '2017-01-16', '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20', '2017-01-21', '2017-01-22', '2017-01-23', '2017-01-24', '2017-01-25', '2017-01-26', '2017-01-27', '2017-01-28', '2017-01-29', '2017-01-30', '2017-01-31', '2017-02-01', '2017-02-02', '2017-02-03', '2017-02-04', '2017-02-05', '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09', '2017-02-10', '2017-02-11', '2017-02-12', '2017-02-13', '2017-02-14', '2017-02-15', '2017-02-16', '2017-02-17', '2017-02-18', '2017-02-19', '2017-02-20', '2017-02-21', '2017-02-22', '2017-02-23', '2017-02-24', '2017-02-25', '2017-02-26', '2017-02-27', '2017-02-28', '2017-03-01', '2017-03-02', '2017-03-03', '2017-03-04', '2017-03-05', '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09', '2017-03-10', '2017-03-11', '2017-03-12', '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-17', '2017-03-18', '2017-03-19', '2017-03-20', '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24', '2017-03-25', '2017-03-26', '2017-03-27', '2017-03-28', '2017-03-29', '2017-03-30', '2017-03-31', '2017-04-01', '2017-04-02', '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06', '2017-04-07', '2017-04-08', '2017-04-09', '2017-04-10', '2017-04-11', '2017-04-12', '2017-04-13', '2017-04-14', '2017-04-15', '2017-04-16', '2017-04-17', '2017-04-18', '2017-04-19', '2017-04-20', '2017-04-21', '2017-04-22', '2017-04-23', '2017-04-24', '2017-04-25', '2017-04-26', '2017-04-27', '2017-04-28', '2017-04-29', '2017-04-30', '2017-05-01', '2017-05-02', '2017-05-03', '2017-05-04', '2017-05-05', '2017-05-06', '2017-05-07', '2017-05-08', '2017-05-09', '2017-05-10', '2017-05-11', '2017-05-12', '2017-05-13', '2017-05-14', '2017-05-15', '2017-05-16', '2017-05-17', '2017-05-18', '2017-05-19', '2017-05-20', '2017-05-21', '2017-05-22', '2017-05-23', '2017-05-24', '2017-05-25', '2017-05-26', '2017-05-27', '2017-05-28', '2017-05-29', '2017-05-30', '2017-05-31']

### astropy.time

표준시나 세계시 정도는 datetime을 사용해도 무방하지만 천문학에서 사용하는 시간에는 조금 부족합니다. 천문학에서 사용하는 시간계는 datetime 모듈보다는 astropy.time 모듈을 사용하기를 권장합니다.

#### 세계시

In [19]:
from astropy.time import Time

t_kst_now = Time.now()
print("현재 시각(KST=GMT+9) :", t_kst_now)

t_ut_now = Time(datetime.utcnow(), scale='utc', location=('127d', '37d'))
print("현재 시각(UTC) :", t_ut_now)

print("type(t_ut_now) ;", type(t_ut_now))

현재 시각(KST=GMT+9) : 2023-12-03 10:40:55.594685
현재 시각(UTC) : 2023-12-03 10:40:55.595217
type(t_ut_now) ; <class 'astropy.time.core.Time'>

#### dir함수로 메쏘드 알아보기

In [20]:
print("dir(t_ut_now) ;", dir(t_ut_now))

dir(t_ut_now) ; ['FORMATS', 'SCALES', 'T', '_APPLICABLE_FUNCTIONS', '_METHOD_FUNCTIONS', '__abstractmethods__', '__add__', '__array_function__', '__array_priority__', '__bool__', '__class__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__weakref__', '_abc_impl', '_advanced_index', '_apply', '_astropy_column_attrs', '_call_erfa', '_format', '_get_delta_tdb_tt', '_get_delta_ut1_utc', '_get_time_fmt', '_init_from_vals', '_make_value_equivalent', '_match_shape', '_set_delta_tdb_tt', '_set_delta_ut1_utc', '_set_scale', '_shaped_like_input', '_sid_time_or_earth_rot_ang', '_time', '_time_comparison', 'argmax', 'argmin', 'argsort', 'byear', 'byear_str', 'cache', 'copy', 'cxcsec', 'datetime', 'datetime64', 'decimalyear', 'delta_tdb_tt', 'delta_ut1_utc', 'diagonal', 'earth_rotation_angle', 'fits', 'flatten', 'format', 'get_delta_ut1_utc', 'gps', 'in_subfmt', 'info', 'insert', 'isclose', 'iso', 'isot', 'isscalar', 'jd', 'jd1', 'jd2', 'jyear', 'jyear_str', 'light_travel_time', 'location', 'mask', 'masked', 'max', 'mean', 'min', 'mjd', 'ndim', 'now', 'out_subfmt', 'plot_date', 'precision', 'ptp', 'ravel', 'replicate', 'reshape', 'scale', 'shape', 'sidereal_time', 'size', 'sort', 'squeeze', 'stardate', 'strftime', 'strptime', 'swapaxes', 'tai', 'take', 'tcb', 'tcg', 'tdb', 'to_datetime', 'to_string', 'to_value', 'transpose', 'tt', 'unix', 'unix_tai', 'ut1', 'utc', 'value', 'writeable', 'yday', 'ymdhms']

#### Julian day 구하기

In [21]:
print("t_ut_now.to_value(format='jd') ;", t_ut_now.to_value(format='jd'))

t_ut_now.to_value(format='jd') ; 2460281.945087908

#### 항성시

In [22]:
print("t_ut_now.sidereal_time('mean') :", t_ut_now.sidereal_time('mean'))

t_ut_now.sidereal_time('mean') : 23h56m57.41770781s

#### astropy.time 이용하여 list 생성

일정 시간 간격으로 시뮬레이션 하려면 시간 간격의 리스트를 미리 만들어 두면 편리할 것입니다. 다음은 Python의 astropy.time을 이용하여 일정 시간 간격의 목록(list)을 만드는 방법입니다.

In [23]:
import numpy as np
from astropy.time import Time, TimeDelta

start_time_text = "2023-12-03"
end_time_text = "2023-12-31"
dt = 1

def astropyTime_range(start_t, end_t, delta):
    '''
        Parameters
        ----------
        start_t : datetime.datetime
        end_t : datetime.datetime
        delta : int
    '''
    current = start_t
    while current < end_t:
        yield current
        current += delta

dts = [dt for dt in
        astropyTime_range(Time(start_time_text), Time(end_time_text),
        TimeDelta(dt, format='jd'))]

print(len(dts))
print(dts)

28
[<Time object: scale='utc' format='iso' value=2023-12-03 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-04 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-05 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-06 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-07 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-08 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-09 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-10 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-11 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-12 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-13 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-14 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-15 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-16 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-17 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-18 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-19 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-20 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-21 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-22 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-23 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-24 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-25 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-26 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-27 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-28 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-29 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-12-30 00:00:00.000>]

## What's observable

[What's observable](https://ssd.jpl.nasa.gov/tools/sbwobs.html) 에서는 관측소 코드와 관측 조건들을 설정하여 소행성과 혜성의 관측 대상의 정보를 얻을 수 있습니다.

### Horizons API

[Horizons API](https://ssd-api.jpl.nasa.gov/doc/horizons.html)를 제공하고 있어 requests로 받아아올 url을 만들수 있습니다.

#### 검색 조건 설정

먼저 조건들을 변수로 설정해 보겠습니다.

In [24]:
#############################################
# variables
mpc_code='P64' # Observer Location: GSHS Observatory, Suwon [code: P64]

#관측 시각 설정 (현재 시각)
t_ut_now = Time(datetime.utcnow(), scale='utc', location=('127d', '37d'))
print("type(obs_dt_utc) :", type(t_ut_now))
print("현재 시각(UTC) :", t_ut_now)

#관측 시각 설정 (임의의 시각)
# t_ut_now = Time(datetime(2023, 10, 2, 10, 0, 0), scale='utc', location=('127d', '37d'))
# print("type(obs_dt_utc) :", type(t_ut_now))
# print("현재 시각(UTC) :", t_ut_now)

obs_datetime = t_ut_now.strftime('%Y-%m-%d %H:%M:%S')
print("obs_datetime :", obs_datetime)
obs_date = t_ut_now.strftime('%Y%m%d')
print("obs_date :", obs_date)

elev_min=60  #
time_min=15
vmag_min=6
vmag_max=13
list_num=100
sort='trans'

type(obs_dt_utc) : <class 'astropy.time.core.Time'>
현재 시각(UTC) : 2023-12-03 10:41:15.233755
obs_datetime : 2023-12-03 10:41:15
obs_date : 20231203

#### url 만들기

In [25]:
# Define API URL and SPK filename:
url = 'https://ssd-api.jpl.nasa.gov/sbwobs.api'
spk_filename = 'spk_file.bsp'

# Get the requested SPK-ID from the command-line:
if (len(sys.argv)) == 1:
  print("please specify SPK-ID on the command-line")
  sys.exit(2)
spkid = sys.argv[1]

# Build the appropriate URL for this API request:
# IMPORTANT: You must encode the "=" as "%3D" and the ";" as "%3B" in the
#            Horizons COMMAND parameter specification.
url += f"?sb-kind=a&mpc-code={mpc_code}&obs-time={str(obs_datetime)}&elev-min={elev_min}&time-min={time_min}"
url += f"&vmag-max={vmag_max}&vmag-min={vmag_min}&optical=true&fmt-ra-dec=true&mag-required=true&output-sort={sort}&maxoutput={list_num}"

print("url :", url)

url : https://ssd-api.jpl.nasa.gov/sbwobs.api?sb-kind=a&mpc-code=P64&obs-time=2023-12-03 10:41:15&elev-min=60&time-min=15&vmag-max=13&vmag-min=6&optical=true&fmt-ra-dec=true&mag-required=true&output-sort=trans&maxoutput=100

### reauests.get

api에서 제공하는 내용을 json 형태로 받아 보겠습니다.

In [28]:
import json
import requests

# Submit the API request and decode the JSON-response:
response = requests.get(url)
try:
  data = json.loads(response.text)
  print(data)
except ValueError:
  print("Unable to decode JSON results")

{'signature': {'source': 'NASA/JPL Small-Body Observability API', 'version': '1.0'}, 'obs_constraints': {'time-min': '15', 'mpc-code': 'P64', 'fmt-ra-dec': 'true', 'output-sort': 'trans', 'obs-time': '2023-12-03 10:41:15', 'maxoutput': '100', 'mag-required': 'true', 'optical': 'true', 'elev-min': '60', 'vmag-max': '13', 'vmag-min': '6'}, 'sb_constraints': {'sb-kind': 'a'}, 'location': 'GSHS Observatory, Suwon', 'obs_night': {'sun_set_az': '242.8', 'sun_set': '2023-12-02 08:13', 'end_civil': '2023-12-02 08:41', 'end_nautical': '2023-12-02 09:14', 'end_astronomical': '2023-12-02 09:45', 'begin_astronomical': '2023-12-02 20:54', 'begin_nautical': '2023-12-02 21:25', 'begin_civil': '2023-12-02 21:58', 'sun_rise_az': '117.3', 'sun_rise': '2023-12-02 22:26', 'transit_phase': '0.72', 'transit': '2023-12-02 19:56 ', 'moon_set_phase': '0.70', 'moon_set': '2023-12-03 03:15 ', 'moon_rise_phase': '0.74', 'moon_rise': '2023-12-02 12:30 ', 'begin_dark': '2023-12-02 09:45', 'mid_dark': '2023-12-02 15:20', 'end_dark': '2023-12-02 20:54', 'dark_time': '11:08'}, 'fields': ['Designation', 'Full name', 'Rise time', 'Transit time', 'Set time', 'Max. time observable', 'R.A.', 'Dec.', 'Vmag', 'Helio. range (au)', 'Topo.range (au)', 'Object-Observer-Sun (deg)', 'Object-Observer-Moon (deg)', 'Galactic latitude (deg)'], 'sort_by': 'transit time (asc.)', 'data': [['602', '602 Marianna (A906 DJ)', '08:56*', '10:18', '11:40', '01:55', '23:30:48', '+13 32\'46"', '12.9', '2.31', '1.81', '107.94', '129.8', '-44.86'], ['678', '678 Fredegundis (A909 BQ)', '10:02', '10:53', '11:44', '01:42', '00:05:34', '+09 39\'20"', '12.8', '2.01', '1.39', '114.68', '125.7', '-51.61'], ['639', '639 Latona (A907 OA)', '10:08', '11:54', '13:40', '03:32', '01:06:33', '+18 22\'35"', '13.0', '2.77', '2.02', '131.36', '108.6', '-44.50'], ['123', '123 Brunhild (A872 OB)', '10:17', '12:02', '13:48', '03:30', '01:15:04', '+18 13\'43"', '12.9', '2.41', '1.62', '133.29', '106.9', '-44.45'], ['135', '135 Hertha (A874 DA)', '10:58', '12:09', '13:19', '02:21', '01:21:31', '+11 51\'59"', '11.9', '2.23', '1.43', '133.01', '108.6', '-50.51'], ['127', '127 Johanna (A872 VB)', '11:12', '12:38', '14:04', '02:52', '01:51:05', '+14 14\'21"', '12.9', '2.71', '1.88', '140.59', '101.1', '-46.39'], ['509', '509 Iolanda (A903 HD)', '11:52', '12:43', '13:33', '01:40', '01:55:33', '+09 32\'47"', '12.9', '2.80', '1.97', '140.00', '102.2', '-50.40'], ['21', '21 Lutetia (A852 VA)', '12:00', '13:00', '14:00', '02:00', '02:12:57', '+10 34\'44"', '10.9', '2.29', '1.42', '144.34', '97.83', '-47.67'], ['93', '93 Minerva (A867 QA)', '11:07', '13:12', '15:17', '04:10', '02:25:09', '+23 49\'02"', '12.5', '2.98', '2.08', '150.28', '89.81', '-34.49'], ['119', '119 Althaea (A872 GA)', '12:18', '13:16', '14:14', '01:56', '02:29:10', '+10 19\'24"', '12.0', '2.41', '1.51', '147.88', '94.28', '-45.94'], ['132', '132 Aethra (A873 LA)', '10:58', '13:22', '15:47', '04:49', '02:35:20', '+32 19\'53"', '12.3', '2.37', '1.46', '151.72', '84.42', '-25.83'], ['139', '139 Juewa (A874 TA)', '11:22', '13:43', '16:05', '04:43', '02:56:26', '+30 41\'30"', '12.4', '2.88', '1.95', '156.48', '80.81', '-25.18'], ['241', '241 Germania (A884 RA)', '11:49', '13:48', '15:47', '03:58', '03:01:08', '+21 56\'17"', '12.1', '2.89', '1.95', '158.44', '82.83', '-32.03'], ['409', '409 Aspasia (A895 XC)', '11:59', '13:48', '15:37', '03:38', '03:00:49', '+19 08\'32"', '11.7', '2.76', '1.82', '157.97', '83.88', '-34.38'], ['154', '154 Bertha (A875 VD)', '11:34', '13:50', '16:06', '04:32', '03:03:13', '+28 00\'25"', '12.8', '3.39', '2.46', '158.55', '80.31', '-26.69'], ['144', '144 Vibilia (A875 LA)', '12:30', '14:03', '15:35', '03:05', '03:15:40', '+15 28\'31"', '10.8', '2.17', '1.21', '160.32', '81.85', '-35.15'], ['895', '895 Helio (A918 NA)', '11:39', '14:08', '16:38', '04:58', '03:21:38', '+35 34\'44"', '12.4', '2.77', '1.83', '159.14', '74.30', '-18.22'], ['363', '363 Padua (A893 FD)', '12:36', '14:24', '16:12', '03:35', '03:37:20', '+18 49\'23"', '12.7', '2.64', '1.67', '166.31', '75.86', '-29.23'], ['481', '481 Emita (A902 CB)', '12:40', '14:25', '16:09', '03:28', '03:37:43', '+17 57\'21"', '11.8', '2.31', '1.34', '166.13', '76.04', '-29.81'], ['182', '182 Elsa (A878 CC)', '12:48', '14:27', '16:06', '03:17', '03:39:58', '+16 43\'05"', '11.1', '1.97', '0.994', '166.17', '75.93', '-30.34'], ['24', '24 Themis (A853 GA)', '12:38', '14:32', '16:26', '03:47', '03:45:16', '+20 19\'10"', '11.6', '3.06', '2.09', '168.47', '73.62', '-26.86'], ['70', '70 Panopaea (A861 JA)', '12:27', '14:36', '16:46', '04:18', '03:49:45', '+25 11\'57"', '12.1', '2.79', '1.81', '169.31', '71.24', '-22.58'], ['503', '503 Evelyn (A903 BL)', '12:48', '14:39', '16:29', '03:40', '03:51:56', '+19 26\'18"', '12.3', '2.36', '1.38', '169.79', '72.39', '-26.41'], ['113', '113 Amalthea (A871 EA)', '13:24', '14:44', '16:04', '02:39', '03:57:28', '+13 13\'00"', '11.9', '2.52', '1.55', '167.62', '73.06', '-29.77'], ['65', '65 Cybele (A861 EB)', '13:14', '14:49', '16:23', '03:08', '04:01:55', '+15 48\'07"', '12.4', '3.83', '2.85', '170.18', '71.22', '-27.23'], ['306', '306 Unitas (A891 EA)', '14:11', '14:56', '15:41', '01:29', '04:09:20', '+09 04\'21"', '12.1', '2.46', '1.49', '165.78', '71.69', '-30.24'], ['346', '346 Hermentaria (A892 WC)', '13:28', '14:57', '16:25', '02:56', '04:09:48', '+14 36\'52"', '10.8', '2.57', '1.59', '170.63', '69.78', '-26.60'], ['358', '358 Apollonia (A893 EC)', '13:33', '15:06', '16:40', '03:06', '04:19:38', '+15 36\'16"', '12.2', '2.44', '1.46', '172.75', '67.21', '-24.15'], ['347', '347 Pariana (A892 WD)', '13:34', '15:07', '16:41', '03:06', '04:20:46', '+15 36\'24"', '12.6', '2.66', '1.68', '172.88', '66.95', '-23.94'], ['95', '95 Arethusa (A867 WA)', '13:20', '15:11', '17:02', '03:42', '04:24:09', '+19 40\'20"', '11.4', '2.65', '1.67', '176.71', '65.04', '-20.70'], ['758', '758 Mancunia (A912 KB)', '13:37', '15:14', '16:51', '03:13', '04:27:36', '+16 17\'40"', '12.1', '2.72', '1.74', '174.11', '65.18', '-22.23'], ['480', '480 Hansa (A901 KB)', '13:52', '15:19', '16:46', '02:53', '04:32:18', '+14 22\'58"', '11.6', '2.53', '1.55', '172.39', '64.66', '-22.54'], ['317', '317 Roxane (A891 RD)', '13:45', '15:35', '17:25', '03:39', '04:48:28', '+19 20\'36"', '12.4', '2.28', '1.30', '175.75', '59.58', '-16.45'], ['160', '160 Una (A876 DA)', '13:33', '15:50', '18:07', '04:34', '05:03:09', '+28 28\'50"', '12.5', '2.55', '1.57', '170.78', '54.55', '-8.25'], ['498', '498 Tokio (A902 XA)', '14:17', '15:57', '17:38', '03:20', '05:10:47', '+17 03\'35"', '12.3', '2.57', '1.60', '170.09', '55.02', '-13.47'], ['210', '210 Isabella (A879 VA)', '13:42', '16:01', '18:19', '04:36', '05:14:24', '+29 05\'00"', '12.5', '2.42', '1.44', '168.49', '52.04', '-5.91'], ['389', '389 Industria (A894 EE)', '13:46', '16:03', '18:21', '04:35', '05:16:39', '+28 39\'54"', '11.7', '2.67', '1.69', '168.32', '51.59', '-5.75'], ['159', '159 Aemilia (A876 BA)', '14:49', '16:23', '17:57', '03:08', '05:36:26', '+15 44\'11"', '12.4', '2.83', '1.87', '164.03', '49.42', '-9.02'], ['149', '149 Medusa (A875 SA)', '14:30', '16:28', '18:27', '03:56', '05:41:57', '+21 36\'58"', '12.8', '2.05', '1.08', '164.28', '46.86', '-4.83'], ['407', '407 Arachne (A895 TB)', '14:12', '16:33', '18:54', '04:41', '05:46:45', '+30 13\'57"', '12.7', '2.53', '1.58', '161.78', '44.95', '0.59'], ['704', '704 Interamnia (A910 TC)', '14:18', '16:42', '19:06', '04:47', '05:55:27', '+31 44\'59"', '10.5', '2.81', '1.87', '159.47', '43.09', '2.97'], ['488', '488 Kreusa (A902 MC)', '14:41', '16:45', '18:50', '04:08', '05:59:05', '+23 28\'19"', '12.3', '2.98', '2.03', '160.39', '42.68', '-0.48'], ['37', '37 Fides (A855 TB)', '14:29', '16:46', '19:04', '04:35', '05:59:47', '+28 39\'36"', '10.1', '2.19', '1.23', '159.58', '42.15', '2.24'], ['776', '776 Berbericia (A914 BE)', '14:48', '16:58', '19:08', '04:20', '06:11:32', '+25 39\'29"', '11.4', '2.62', '1.68', '157.48', '39.66', '3.06'], ['4', '4 Vesta (A807 FA)', '15:13', '17:05', '18:56', '03:43', '06:18:21', '+19 45\'22"', '6.83', '2.57', '1.64', '155.60', '38.80', '1.64'], ['9', '9 Metis (A848 HA)', '15:00', '17:11', '19:22', '04:21', '06:24:27', '+25 53\'07"', '8.95', '2.10', '1.16', '154.56', '36.74', '5.73'], ['48', '48 Doris (A857 SA)', '16:00', '17:23', '18:46', '02:45', '06:36:25', '+13 41\'33"', '11.7', '2.91', '2.02', '149.83', '36.07', '2.65'], ['5', '5 Astraea (A845 XA)', '15:57', '17:32', '19:06', '03:08', '06:45:16', '+15 44\'27"', '10.1', '2.24', '1.33', '148.44', '33.43', '5.49'], ['72', '72 Feronia (A861 KA)', '16:23', '17:53', '19:23', '03:00', '07:06:50', '+14 59\'00"', '12.9', '2.47', '1.61', '143.24', '28.66', '9.83'], ['804', '804 Hispania (A915 FK)', '15:53', '18:27', '21:02*', '05:01', '07:41:09', '+41 35\'21"', '13.0', '3.02', '2.23', '136.37', '26.58', '26.19'], ['92', '92 Undina (A867 NA)', '16:32', '18:30', '20:27', '03:55', '07:43:49', '+21 25\'16"', '12.2', '3.34', '2.56', '136.14', '18.76', '20.46'], ['128', '128 Nemesis (A872 WA)', '17:31', '19:33', '21:35*', '03:22', '08:47:05', '+22 39\'47"', '12.4', '2.71', '2.05', '121.99', '4.175', '34.66'], ['71', '71 Niobe (A861 PA)', '17:27', '19:48', '22:09*', '03:27', '09:01:55', '+30 27\'10"', '12.0', '2.87', '2.24', '120.20', '8.859', '39.85'], ['78', '78 Diana (A863 EA)', '17:55', '20:03', '22:11*', '02:59', '09:17:07', '+24 56\'32"', '12.1', '2.11', '1.48', '115.81', '4.408', '41.90'], ['38', '38 Leda (A856 AA)', '19:03', '20:25', '21:47*', '01:51', '09:38:56', '+13 34\'10"', '12.8', '2.34', '1.84', '107.64', '11.48', '42.95'], ['118', '118 Peitho (A872 EA)', '18:43', '20:44', '22:45*', '02:10', '09:58:29', '+22 30\'05"', '12.8', '2.09', '1.60', '106.04', '12.53', '50.40'], ['451', '451 Patientia (A899 XA)', '18:40', '20:44', '22:48*', '02:14', '09:58:14', '+23 32\'18"', '12.1', '2.94', '2.51', '106.40', '12.54', '50.62'], ['192', '192 Nausikaa (A879 DA)', '19:15', '20:54*', '22:34*', '01:39', '10:08:21', '+16 52\'02"', '12.0', '2.47', '2.07', '102.03', '15.78', '50.77'], ['63', '63 Ausonia (A861 CA)', '19:49', '21:09*', '22:29*', '01:04', '10:23:47', '+13 14\'07"', '12.0', '2.62', '2.31', '97.28', '20.65', '52.63'], ['372', '372 Palma (A893 QB)', '19:33', '21:19*', '23:05*', '01:20', '10:33:41', '+18 20\'48"', '12.2', '2.52', '2.20', '96.88', '21.18', '56.92'], ['349', '349 Dembowska (A892 XB)', '20:24', '21:52*', '23:19*', '00:30', '11:06:05', '+14 33\'00"', '11.5', '3.06', '2.93', '88.25', '29.68', '62.25'], ['31', '31 Euphrosyne (A854 RA)', '19:26', '21:58*', '00:30*', '01:28', '11:12:17', '+38 02\'22"', '11.8', '2.55', '2.25', '96.31', '31.97', '66.25'], ['23', '23 Thalia (A852 XA)', '20:29', '22:03*', '23:38*', '00:24', '11:17:46', '+15 47\'45"', '11.3', '2.02', '1.83', '86.17', '32.02', '65.31']], 'total_objects': '63', 'shown_objects': '63'}

안에 들어 있는 데이터를 확인해 보곘습니다.

In [29]:
print("type(data) :", type(data))
print("data.keys :", data.keys)

type(data) : <class 'dict'>
data.keys : <built-in method keys of dict object at 0x7efd6cce2a00>

 아마도 data['fields']에 있는 것이 필요한 자료인것 같습니다.

In [30]:
print(data['obs_constraints'])
print(data['sb_constraints'])
print(data['fields'])
print(data['data'])
print(type(data['fields']))
print(len(data['fields']))
print(len(data['data'][0]))

{'time-min': '15', 'mpc-code': 'P64', 'fmt-ra-dec': 'true', 'output-sort': 'trans', 'obs-time': '2023-12-03 10:41:15', 'maxoutput': '100', 'mag-required': 'true', 'optical': 'true', 'elev-min': '60', 'vmag-max': '13', 'vmag-min': '6'}
{'sb-kind': 'a'}
['Designation', 'Full name', 'Rise time', 'Transit time', 'Set time', 'Max. time observable', 'R.A.', 'Dec.', 'Vmag', 'Helio. range (au)', 'Topo.range (au)', 'Object-Observer-Sun (deg)', 'Object-Observer-Moon (deg)', 'Galactic latitude (deg)']
[['602', '602 Marianna (A906 DJ)', '08:56*', '10:18', '11:40', '01:55', '23:30:48', '+13 32\'46"', '12.9', '2.31', '1.81', '107.94', '129.8', '-44.86'], ['678', '678 Fredegundis (A909 BQ)', '10:02', '10:53', '11:44', '01:42', '00:05:34', '+09 39\'20"', '12.8', '2.01', '1.39', '114.68', '125.7', '-51.61'], ['639', '639 Latona (A907 OA)', '10:08', '11:54', '13:40', '03:32', '01:06:33', '+18 22\'35"', '13.0', '2.77', '2.02', '131.36', '108.6', '-44.50'], ['123', '123 Brunhild (A872 OB)', '10:17', '12:02', '13:48', '03:30', '01:15:04', '+18 13\'43"', '12.9', '2.41', '1.62', '133.29', '106.9', '-44.45'], ['135', '135 Hertha (A874 DA)', '10:58', '12:09', '13:19', '02:21', '01:21:31', '+11 51\'59"', '11.9', '2.23', '1.43', '133.01', '108.6', '-50.51'], ['127', '127 Johanna (A872 VB)', '11:12', '12:38', '14:04', '02:52', '01:51:05', '+14 14\'21"', '12.9', '2.71', '1.88', '140.59', '101.1', '-46.39'], ['509', '509 Iolanda (A903 HD)', '11:52', '12:43', '13:33', '01:40', '01:55:33', '+09 32\'47"', '12.9', '2.80', '1.97', '140.00', '102.2', '-50.40'], ['21', '21 Lutetia (A852 VA)', '12:00', '13:00', '14:00', '02:00', '02:12:57', '+10 34\'44"', '10.9', '2.29', '1.42', '144.34', '97.83', '-47.67'], ['93', '93 Minerva (A867 QA)', '11:07', '13:12', '15:17', '04:10', '02:25:09', '+23 49\'02"', '12.5', '2.98', '2.08', '150.28', '89.81', '-34.49'], ['119', '119 Althaea (A872 GA)', '12:18', '13:16', '14:14', '01:56', '02:29:10', '+10 19\'24"', '12.0', '2.41', '1.51', '147.88', '94.28', '-45.94'], ['132', '132 Aethra (A873 LA)', '10:58', '13:22', '15:47', '04:49', '02:35:20', '+32 19\'53"', '12.3', '2.37', '1.46', '151.72', '84.42', '-25.83'], ['139', '139 Juewa (A874 TA)', '11:22', '13:43', '16:05', '04:43', '02:56:26', '+30 41\'30"', '12.4', '2.88', '1.95', '156.48', '80.81', '-25.18'], ['241', '241 Germania (A884 RA)', '11:49', '13:48', '15:47', '03:58', '03:01:08', '+21 56\'17"', '12.1', '2.89', '1.95', '158.44', '82.83', '-32.03'], ['409', '409 Aspasia (A895 XC)', '11:59', '13:48', '15:37', '03:38', '03:00:49', '+19 08\'32"', '11.7', '2.76', '1.82', '157.97', '83.88', '-34.38'], ['154', '154 Bertha (A875 VD)', '11:34', '13:50', '16:06', '04:32', '03:03:13', '+28 00\'25"', '12.8', '3.39', '2.46', '158.55', '80.31', '-26.69'], ['144', '144 Vibilia (A875 LA)', '12:30', '14:03', '15:35', '03:05', '03:15:40', '+15 28\'31"', '10.8', '2.17', '1.21', '160.32', '81.85', '-35.15'], ['895', '895 Helio (A918 NA)', '11:39', '14:08', '16:38', '04:58', '03:21:38', '+35 34\'44"', '12.4', '2.77', '1.83', '159.14', '74.30', '-18.22'], ['363', '363 Padua (A893 FD)', '12:36', '14:24', '16:12', '03:35', '03:37:20', '+18 49\'23"', '12.7', '2.64', '1.67', '166.31', '75.86', '-29.23'], ['481', '481 Emita (A902 CB)', '12:40', '14:25', '16:09', '03:28', '03:37:43', '+17 57\'21"', '11.8', '2.31', '1.34', '166.13', '76.04', '-29.81'], ['182', '182 Elsa (A878 CC)', '12:48', '14:27', '16:06', '03:17', '03:39:58', '+16 43\'05"', '11.1', '1.97', '0.994', '166.17', '75.93', '-30.34'], ['24', '24 Themis (A853 GA)', '12:38', '14:32', '16:26', '03:47', '03:45:16', '+20 19\'10"', '11.6', '3.06', '2.09', '168.47', '73.62', '-26.86'], ['70', '70 Panopaea (A861 JA)', '12:27', '14:36', '16:46', '04:18', '03:49:45', '+25 11\'57"', '12.1', '2.79', '1.81', '169.31', '71.24', '-22.58'], ['503', '503 Evelyn (A903 BL)', '12:48', '14:39', '16:29', '03:40', '03:51:56', '+19 26\'18"', '12.3', '2.36', '1.38', '169.79', '72.39', '-26.41'], ['113', '113 Amalthea (A871 EA)', '13:24', '14:44', '16:04', '02:39', '03:57:28', '+13 13\'00"', '11.9', '2.52', '1.55', '167.62', '73.06', '-29.77'], ['65', '65 Cybele (A861 EB)', '13:14', '14:49', '16:23', '03:08', '04:01:55', '+15 48\'07"', '12.4', '3.83', '2.85', '170.18', '71.22', '-27.23'], ['306', '306 Unitas (A891 EA)', '14:11', '14:56', '15:41', '01:29', '04:09:20', '+09 04\'21"', '12.1', '2.46', '1.49', '165.78', '71.69', '-30.24'], ['346', '346 Hermentaria (A892 WC)', '13:28', '14:57', '16:25', '02:56', '04:09:48', '+14 36\'52"', '10.8', '2.57', '1.59', '170.63', '69.78', '-26.60'], ['358', '358 Apollonia (A893 EC)', '13:33', '15:06', '16:40', '03:06', '04:19:38', '+15 36\'16"', '12.2', '2.44', '1.46', '172.75', '67.21', '-24.15'], ['347', '347 Pariana (A892 WD)', '13:34', '15:07', '16:41', '03:06', '04:20:46', '+15 36\'24"', '12.6', '2.66', '1.68', '172.88', '66.95', '-23.94'], ['95', '95 Arethusa (A867 WA)', '13:20', '15:11', '17:02', '03:42', '04:24:09', '+19 40\'20"', '11.4', '2.65', '1.67', '176.71', '65.04', '-20.70'], ['758', '758 Mancunia (A912 KB)', '13:37', '15:14', '16:51', '03:13', '04:27:36', '+16 17\'40"', '12.1', '2.72', '1.74', '174.11', '65.18', '-22.23'], ['480', '480 Hansa (A901 KB)', '13:52', '15:19', '16:46', '02:53', '04:32:18', '+14 22\'58"', '11.6', '2.53', '1.55', '172.39', '64.66', '-22.54'], ['317', '317 Roxane (A891 RD)', '13:45', '15:35', '17:25', '03:39', '04:48:28', '+19 20\'36"', '12.4', '2.28', '1.30', '175.75', '59.58', '-16.45'], ['160', '160 Una (A876 DA)', '13:33', '15:50', '18:07', '04:34', '05:03:09', '+28 28\'50"', '12.5', '2.55', '1.57', '170.78', '54.55', '-8.25'], ['498', '498 Tokio (A902 XA)', '14:17', '15:57', '17:38', '03:20', '05:10:47', '+17 03\'35"', '12.3', '2.57', '1.60', '170.09', '55.02', '-13.47'], ['210', '210 Isabella (A879 VA)', '13:42', '16:01', '18:19', '04:36', '05:14:24', '+29 05\'00"', '12.5', '2.42', '1.44', '168.49', '52.04', '-5.91'], ['389', '389 Industria (A894 EE)', '13:46', '16:03', '18:21', '04:35', '05:16:39', '+28 39\'54"', '11.7', '2.67', '1.69', '168.32', '51.59', '-5.75'], ['159', '159 Aemilia (A876 BA)', '14:49', '16:23', '17:57', '03:08', '05:36:26', '+15 44\'11"', '12.4', '2.83', '1.87', '164.03', '49.42', '-9.02'], ['149', '149 Medusa (A875 SA)', '14:30', '16:28', '18:27', '03:56', '05:41:57', '+21 36\'58"', '12.8', '2.05', '1.08', '164.28', '46.86', '-4.83'], ['407', '407 Arachne (A895 TB)', '14:12', '16:33', '18:54', '04:41', '05:46:45', '+30 13\'57"', '12.7', '2.53', '1.58', '161.78', '44.95', '0.59'], ['704', '704 Interamnia (A910 TC)', '14:18', '16:42', '19:06', '04:47', '05:55:27', '+31 44\'59"', '10.5', '2.81', '1.87', '159.47', '43.09', '2.97'], ['488', '488 Kreusa (A902 MC)', '14:41', '16:45', '18:50', '04:08', '05:59:05', '+23 28\'19"', '12.3', '2.98', '2.03', '160.39', '42.68', '-0.48'], ['37', '37 Fides (A855 TB)', '14:29', '16:46', '19:04', '04:35', '05:59:47', '+28 39\'36"', '10.1', '2.19', '1.23', '159.58', '42.15', '2.24'], ['776', '776 Berbericia (A914 BE)', '14:48', '16:58', '19:08', '04:20', '06:11:32', '+25 39\'29"', '11.4', '2.62', '1.68', '157.48', '39.66', '3.06'], ['4', '4 Vesta (A807 FA)', '15:13', '17:05', '18:56', '03:43', '06:18:21', '+19 45\'22"', '6.83', '2.57', '1.64', '155.60', '38.80', '1.64'], ['9', '9 Metis (A848 HA)', '15:00', '17:11', '19:22', '04:21', '06:24:27', '+25 53\'07"', '8.95', '2.10', '1.16', '154.56', '36.74', '5.73'], ['48', '48 Doris (A857 SA)', '16:00', '17:23', '18:46', '02:45', '06:36:25', '+13 41\'33"', '11.7', '2.91', '2.02', '149.83', '36.07', '2.65'], ['5', '5 Astraea (A845 XA)', '15:57', '17:32', '19:06', '03:08', '06:45:16', '+15 44\'27"', '10.1', '2.24', '1.33', '148.44', '33.43', '5.49'], ['72', '72 Feronia (A861 KA)', '16:23', '17:53', '19:23', '03:00', '07:06:50', '+14 59\'00"', '12.9', '2.47', '1.61', '143.24', '28.66', '9.83'], ['804', '804 Hispania (A915 FK)', '15:53', '18:27', '21:02*', '05:01', '07:41:09', '+41 35\'21"', '13.0', '3.02', '2.23', '136.37', '26.58', '26.19'], ['92', '92 Undina (A867 NA)', '16:32', '18:30', '20:27', '03:55', '07:43:49', '+21 25\'16"', '12.2', '3.34', '2.56', '136.14', '18.76', '20.46'], ['128', '128 Nemesis (A872 WA)', '17:31', '19:33', '21:35*', '03:22', '08:47:05', '+22 39\'47"', '12.4', '2.71', '2.05', '121.99', '4.175', '34.66'], ['71', '71 Niobe (A861 PA)', '17:27', '19:48', '22:09*', '03:27', '09:01:55', '+30 27\'10"', '12.0', '2.87', '2.24', '120.20', '8.859', '39.85'], ['78', '78 Diana (A863 EA)', '17:55', '20:03', '22:11*', '02:59', '09:17:07', '+24 56\'32"', '12.1', '2.11', '1.48', '115.81', '4.408', '41.90'], ['38', '38 Leda (A856 AA)', '19:03', '20:25', '21:47*', '01:51', '09:38:56', '+13 34\'10"', '12.8', '2.34', '1.84', '107.64', '11.48', '42.95'], ['118', '118 Peitho (A872 EA)', '18:43', '20:44', '22:45*', '02:10', '09:58:29', '+22 30\'05"', '12.8', '2.09', '1.60', '106.04', '12.53', '50.40'], ['451', '451 Patientia (A899 XA)', '18:40', '20:44', '22:48*', '02:14', '09:58:14', '+23 32\'18"', '12.1', '2.94', '2.51', '106.40', '12.54', '50.62'], ['192', '192 Nausikaa (A879 DA)', '19:15', '20:54*', '22:34*', '01:39', '10:08:21', '+16 52\'02"', '12.0', '2.47', '2.07', '102.03', '15.78', '50.77'], ['63', '63 Ausonia (A861 CA)', '19:49', '21:09*', '22:29*', '01:04', '10:23:47', '+13 14\'07"', '12.0', '2.62', '2.31', '97.28', '20.65', '52.63'], ['372', '372 Palma (A893 QB)', '19:33', '21:19*', '23:05*', '01:20', '10:33:41', '+18 20\'48"', '12.2', '2.52', '2.20', '96.88', '21.18', '56.92'], ['349', '349 Dembowska (A892 XB)', '20:24', '21:52*', '23:19*', '00:30', '11:06:05', '+14 33\'00"', '11.5', '3.06', '2.93', '88.25', '29.68', '62.25'], ['31', '31 Euphrosyne (A854 RA)', '19:26', '21:58*', '00:30*', '01:28', '11:12:17', '+38 02\'22"', '11.8', '2.55', '2.25', '96.31', '31.97', '66.25'], ['23', '23 Thalia (A852 XA)', '20:29', '22:03*', '23:38*', '00:24', '11:17:46', '+15 47\'45"', '11.3', '2.02', '1.83', '86.17', '32.02', '65.31']]
<class 'list'>
14
14

### dataframe 만들기

아무래도 가장 다루기 쉬운 데이타 형태인 dataframe으로 만들어 보겠습니다.

In [31]:
import pandas as pd

df = pd.DataFrame.from_dict(data['data'])
df = df.set_axis((data['fields']), axis=1)
df['OBSdate(UT)'] = obs_date
df

,Designation,Full name,Rise time,Transit time,Set time,Max. time observable,R.A.,Dec.,Vmag,Helio. range (au),Topo.range (au),Object-Observer-Sun (deg),Object-Observer-Moon (deg),Galactic latitude (deg),OBSdate(UT)
0,602,602 Marianna (A906 DJ),08:56*,10:18,11:40,01:55,23:30:48,"+13 32'46""",12.9,2.31,1.81,107.94,129.8,-44.86,20231203
1,678,678 Fredegundis (A909 BQ),10:02,10:53,11:44,01:42,00:05:34,"+09 39'20""",12.8,2.01,1.39,114.68,125.7,-51.61,20231203
2,639,639 Latona (A907 OA),10:08,11:54,13:40,03:32,01:06:33,"+18 22'35""",13.0,2.77,2.02,131.36,108.6,-44.50,20231203
3,123,123 Brunhild (A872 OB),10:17,12:02,13:48,03:30,01:15:04,"+18 13'43""",12.9,2.41,1.62,133.29,106.9,-44.45,20231203
4,135,135 Hertha (A874 DA),10:58,12:09,13:19,02:21,01:21:31,"+11 51'59""",11.9,2.23,1.43,133.01,108.6,-50.51,20231203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,63,63 Ausonia (A861 CA),19:49,21:09*,22:29*,01:04,10:23:47,"+13 14'07""",12.0,2.62,2.31,97.28,20.65,52.63,20231203
59,372,372 Palma (A893 QB),19:33,21:19*,23:05*,01:20,10:33:41,"+18 20'48""",12.2,2.52,2.20,96.88,21.18,56.92,20231203
60,349,349 Dembowska (A892 XB),20:24,21:52*,23:19*,00:30,11:06:05,"+14 33'00""",11.5,3.06,2.93,88.25,29.68,62.25,20231203
61,31,31 Euphrosyne (A854 RA),19:26,21:58*,00:30*,01:28,11:12:17,"+38 02'22""",11.8,2.55,2.25,96.31,31.97,66.25,20231203
62,23,23 Thalia (A852 XA),20:29,22:03*,23:38*,00:24,11:17:46,"+15 47'45""",11.3,2.02,1.83,86.17,32.02,65.31,20231203

### 관측 계획 저장 폴더 생성

FITS 파일을 저장할 폴더를 "OBSplan_asteroid" 이라는 이름으로 생성해보겠습니다.

* 만약 리눅스 시스템 이라면 shell 명령어로 가능한데, "!"를 붙이면 shell 명령어를 실행할 수 있습니다.
> !mkdir OBSplan_asteroid

OS의 영향을 받지 않기 위하여 pathlib을 사용하여 다음과 같이 폴더를 생성합니다.

In [32]:
import os
from pathlib import Path
BASEPATH = Path("./")
save_dir_name = "OBSplan_asteroid"
print(f"BASEPATH: {BASEPATH}")

if not (BASEPATH/save_dir_name).exists():
    os.mkdir(str(BASEPATH/save_dir_name))
    print (f"{str(BASEPATH/save_dir_name)} is created...")
else :
    print (f"{str(BASEPATH/save_dir_name)} is already exist...")

BASEPATH: .
OBSplan_asteroid is already exist...

### dataframe 저장

In [ ]:
df.to_csv(str(BASEPATH/save_dir_name/ f'asteroid_{obs_date}.csv'))

### (과제)

12월 1달 동안의 NEA 목록을 csv  파일로 저장하는 코드를 완성하세요.

## 소행성 좌표 얻기

### 소행성 id 잘라내기

앞서 얻은 dataframe로 부터 소행성의 이름을 알아보자.

In [ ]:
#print("df :", df)
#print("df['Full name'] :", df['Full name'])
print("df['Full name'][0] :", df['Full name'][0])

#import re
#asteroid_names = re.findall('\(([^)]+)', df['Full name'][0])   #extracts string in bracket()
#print (asteroid_names[0])

asteroid_id = df['Full name'][0].split(" ")[0]   #extracts string in bracket()
print("asteroid_id :", asteroid_id)
obs_date = df['OBSdate(UT)'][0]

df['Full name'][0] : 602 Marianna (A906 DJ)
asteroid_id : 602

### astroquery.mpc

[astroquery.mpc](https://astroquery.readthedocs.io/en/latest/mpc/mpc.html) 를 이용하여 시간에 따른 소행성의 좌표를 얻어보자.

In [ ]:
from astroquery.mpc import MPC
eph = MPC.get_ephemeris(asteroid_id, step='1h', number=30 * 24)
print("type(eph) :", type(eph))
print("eph :", eph)
df_eph = eph.to_pandas()
df_eph

type(eph) : <class 'astropy.table.table.Table'>
eph :           Date                  RA         ... Uncertainty 3sig Unc. P.A.
                               deg         ...      arcsec         deg
----------------------- ------------------ ... ---------------- ---------
2023-12-01 09:00:00.000  352.1704166666666 ...                0      49.2
2023-12-01 10:00:00.000 352.17791666666665 ...                0      49.2
2023-12-01 11:00:00.000  352.1854166666666 ...                0      49.2
2023-12-01 12:00:00.000 352.19333333333327 ...                0      49.2
2023-12-01 13:00:00.000 352.20083333333326 ...                0      49.2
2023-12-01 14:00:00.000 352.20833333333326 ...                0      49.2
2023-12-01 15:00:00.000 352.21583333333325 ...                0      49.2
2023-12-01 16:00:00.000  352.2233333333333 ...                0      49.2
2023-12-01 17:00:00.000 352.23124999999993 ...                0      49.2
2023-12-01 18:00:00.000  352.2387499999999 ...                0      49.2
                    ...                ... ...              ...       ...
2023-12-30 23:00:00.000  359.7845833333333 ...                0      51.4
2023-12-31 00:00:00.000 359.79833333333335 ...                0      51.3
2023-12-31 01:00:00.000 359.81166666666667 ...                0      51.4
2023-12-31 02:00:00.000 359.82499999999993 ...                0      51.4
2023-12-31 03:00:00.000  359.8383333333333 ...                0      51.4
2023-12-31 04:00:00.000  359.8520833333333 ...                0      51.4
2023-12-31 05:00:00.000  359.8654166666666 ...                0      51.4
2023-12-31 06:00:00.000 359.87874999999997 ...                0      51.4
2023-12-31 07:00:00.000           359.8925 ...                0      51.4
2023-12-31 08:00:00.000  359.9058333333333 ...                0      51.4
Length = 720 rows

,Date,RA,Dec,Delta,r,Elongation,Phase,V,Proper motion,Direction,Uncertainty 3sig,Unc. P.A.
0,2023-12-01 09:00:00,352.170417,13.355000,1.793,2.310,108.9,23.8,12.9,27.22,75.5,0,49.2
1,2023-12-01 10:00:00,352.177917,13.356944,1.793,2.310,108.9,23.8,12.9,27.26,75.5,0,49.2
2,2023-12-01 11:00:00,352.185417,13.358889,1.794,2.310,108.9,23.8,12.9,27.30,75.5,0,49.2
3,2023-12-01 12:00:00,352.193333,13.360556,1.794,2.310,108.8,23.8,12.9,27.33,75.5,0,49.2
4,2023-12-01 13:00:00,352.200833,13.362500,1.795,2.310,108.8,23.8,12.9,27.37,75.5,0,49.2
...,...,...,...,...,...,...,...,...,...,...,...,...
715,2023-12-31 04:00:00,359.852083,15.559444,2.151,2.324,87.4,25.0,13.4,49.05,72.2,0,51.4
716,2023-12-31 05:00:00,359.865417,15.563889,2.151,2.324,87.4,25.0,13.4,49.07,72.2,0,51.4
717,2023-12-31 06:00:00,359.878750,15.568056,2.152,2.324,87.4,25.0,13.4,49.10,72.2,0,51.4
718,2023-12-31 07:00:00,359.892500,15.572222,2.152,2.324,87.3,25.0,13.4,49.12,72.2,0,51.4
719,2023-12-31 08:00:00,359.905833,15.576389,2.153,2.324,87.3,25.0,13.4,49.14,72.1,0,51.4

### 최대 움직임 속도 알아보기

In [ ]:
print(f"Proper motion: {eph['Proper motion'].quantity.to('arcmin/h').max():.03f}")

Proper motion: 0.819 arcmin / h

### 파일 저장하기

In [ ]:
eph = MPC.get_ephemeris(asteroid_id, location='P64',
                        ra_format={'sep': ':', 'unit': 'hourangle', 'precision': 1},
                        dec_format={'sep': ':', 'precision': 0},
                        step='1h')
print("type(eph): ", type(eph))
#print("eph: ", eph)
df_eph = eph.to_pandas()
df_eph['Asteroid ID'] = asteroid_id
df_eph['Asteroid name'] = df['Full name'][0]
df_eph.to_csv(str(BASEPATH/save_dir_name/ f'asteroid_{asteroid_id}.csv'))
df_eph

type(eph):  <class 'astropy.table.table.Table'>

,Date,RA,Dec,Delta,r,Elongation,Phase,V,Proper motion,Direction,Azimuth,Altitude,Sun altitude,Moon phase,Moon distance,Moon altitude,Uncertainty 3sig,Unc. P.A.,Asteroid ID,Asteroid name
0,2023-12-01 09:00:00,23:28:41.0,13:21:16,1.793,2.31,108.9,23.8,12.9,26.31,74.8,138,60,-9,0.84,115,-20,0,49.2,602,602 Marianna (A906 DJ)
1,2023-12-01 10:00:00,23:28:42.8,13:21:23,1.793,2.31,108.9,23.8,12.9,26.28,74.9,168,66,-21,0.84,116,-13,0,49.2,602,602 Marianna (A906 DJ)
2,2023-12-01 11:00:00,23:28:44.5,13:21:30,1.794,2.31,108.9,23.8,12.9,26.31,75.0,203,65,-33,0.83,116,-4,0,49.2,602,602 Marianna (A906 DJ)
3,2023-12-01 12:00:00,23:28:46.2,13:21:36,1.794,2.31,108.8,23.8,12.9,26.41,75.2,230,57,-45,0.83,117,6,0,49.2,602,602 Marianna (A906 DJ)
4,2023-12-01 13:00:00,23:28:48.0,13:21:43,1.795,2.31,108.8,23.8,12.9,26.57,75.4,247,47,-56,0.83,117,16,0,49.2,602,602 Marianna (A906 DJ)
5,2023-12-01 14:00:00,23:28:49.8,13:21:50,1.795,2.31,108.8,23.8,12.9,26.79,75.6,259,36,-67,0.82,118,27,0,49.2,602,602 Marianna (A906 DJ)
6,2023-12-01 15:00:00,23:28:51.6,13:21:56,1.796,2.31,108.7,23.8,12.9,27.05,75.8,269,24,-74,0.82,118,38,0,49.2,602,602 Marianna (A906 DJ)
7,2023-12-01 16:00:00,23:28:53.4,13:22:03,1.796,2.31,108.7,23.9,12.9,27.34,75.9,278,12,-72,0.82,118,50,0,49.2,602,602 Marianna (A906 DJ)
8,2023-12-01 17:00:00,23:28:55.2,13:22:10,1.797,2.31,108.7,23.9,12.9,27.64,76.0,287,0,-63,0.81,119,61,0,49.2,602,602 Marianna (A906 DJ)
9,2023-12-01 18:00:00,23:28:57.0,13:22:16,1.797,2.31,108.6,23.9,12.9,27.93,76.1,296,-11,-52,0.81,119,71,0,49.2,602,602 Marianna (A906 DJ)
10,2023-12-01 19:00:00,23:28:58.9,13:22:23,1.798,2.31,108.6,23.9,12.9,28.19,76.2,307,-21,-40,0.81,120,77,0,49.2,602,602 Marianna (A906 DJ)
11,2023-12-01 20:00:00,23:29:00.8,13:22:30,1.798,2.31,108.6,23.9,12.9,28.42,76.1,320,-30,-28,0.80,120,73,0,49.2,602,602 Marianna (A906 DJ)
12,2023-12-01 21:00:00,23:29:02.7,13:22:37,1.799,2.31,108.5,23.9,12.9,28.59,76.1,336,-36,-17,0.80,121,63,0,49.2,602,602 Marianna (A906 DJ)
13,2023-12-01 22:00:00,23:29:04.6,13:22:44,1.799,2.31,108.5,23.9,12.9,28.70,76.0,354,-39,-5,0.80,121,52,0,49.2,602,602 Marianna (A906 DJ)
14,2023-12-01 23:00:00,23:29:06.5,13:22:51,1.799,2.31,108.5,23.9,12.9,28.74,75.9,13,-39,5,0.79,122,41,0,49.2,602,602 Marianna (A906 DJ)
15,2023-12-02 00:00:00,23:29:08.4,13:22:58,1.800,2.31,108.4,23.9,12.9,28.71,75.7,30,-34,15,0.79,122,29,0,49.2,602,602 Marianna (A906 DJ)
16,2023-12-02 01:00:00,23:29:10.3,13:23:05,1.800,2.31,108.4,23.9,12.9,28.62,75.5,45,-27,22,0.79,123,18,0,49.2,602,602 Marianna (A906 DJ)
17,2023-12-02 02:00:00,23:29:12.2,13:23:12,1.801,2.31,108.4,23.9,12.9,28.48,75.3,57,-18,28,0.78,123,7,0,49.2,602,602 Marianna (A906 DJ)
18,2023-12-02 03:00:00,23:29:14.1,13:23:19,1.801,2.31,108.3,23.9,12.9,28.30,75.1,67,-7,31,0.78,124,-3,0,49.2,602,602 Marianna (A906 DJ)
19,2023-12-02 04:00:00,23:29:16.0,13:23:26,1.802,2.31,108.3,23.9,12.9,28.09,75.0,77,4,30,0.78,124,-12,0,49.2,602,602 Marianna (A906 DJ)
20,2023-12-02 05:00:00,23:29:17.8,13:23:34,1.802,2.31,108.3,23.9,12.9,27.87,74.8,85,16,26,0.77,125,-20,0,49.2,602,602 Marianna (A906 DJ)
21,2023-12-02 06:00:00,23:29:19.6,13:23:41,1.803,2.31,108.3,23.9,12.9,27.65,74.7,94,28,20,0.77,125,-26,0,49.2,602,602 Marianna (A906 DJ)
22,2023-12-02 07:00:00,23:29:21.5,13:23:48,1.803,2.31,108.2,23.9,12.9,27.47,74.7,105,40,11,0.77,125,-29,0,49.2,602,602 Marianna (A906 DJ)
23,2023-12-02 08:00:00,23:29:23.3,13:23:56,1.804,2.31,108.2,23.9,12.9,27.32,74.7,119,51,2,0.76,126,-29,0,49.2,602,602 Marianna (A906 DJ)
24,2023-12-02 09:00:00,23:29:25.1,13:24:03,1.804,2.31,108.2,23.9,12.9,27.23,74.7,139,61,-9,0.76,126,-27,0,49.2,602,602 Marianna (A906 DJ)
25,2023-12-02 10:00:00,23:29:26.9,13:24:10,1.805,2.31,108.1,23.9,12.9,27.19,74.8,170,66,-21,0.76,127,-21,0,49.2,602,602 Marianna (A906 DJ)
26,2023-12-02 11:00:00,23:29:28.7,13:24:17,1.805,2.31,108.1,23.9,12.9,27.23,74.9,205,64,-33,0.75,127,-14,0,49.2,602,602 Marianna (A906 DJ)
27,2023-12-02 12:00:00,23:29:30.5,13:24:24,1.806,2.31,108.1,23.9,12.9,27.33,75.1,231,57,-45,0.75,128,-5,0,49.2,602,602 Marianna (A906 DJ)
28,2023-12-02 13:00:00,23:29:32.3,13:24:31,1.806,2.31,108.0,23.9,12.9,27.49,75.3,248,47,-56,0.75,128,5,0,49.2,602,602 Marianna (A906 DJ)
29,2023-12-02 14:00:00,23:29:34.1,13:24:38,1.807,2.31,108.0,24.0,12.9,27.71,75.4,260,35,-67,0.74,129,16,0,49.2,602,602 Marianna (A906 DJ)
30,2023-12-02 15:00:00,23:29:36.0,13:24:45,1.807,2.31,108.0,24.0,12.9,27.97,75.6,269,23,-74,0.74,129,27,0,49.2,602,602 Marianna (A906 DJ)
31,2023-12-02 16:00:00,23:29:37.8,13:24:52,1.808,2.31,107.9,24.0,12.9,28.26,75.8,278,11,-73,0.74,130,39,0,49.2,602,602 Marianna (A906 DJ)
32,2023-12-02 17:00:00,23:29:39.7,13:25:00,1.808,2.31,107.9,24.0,12.9,28.56,75.9,287,0,-64,0.73,130,50,0,49.2,602,602 Marianna (A906 DJ)
33,2023-12-02 18:00:00,23:29:41.6,13:25:06,1.808,2.31,107.9,24.0,12.9,28.84,76.0,297,-11,-52,0.73,131,61,0,49.2,602,602 Marianna (A906 DJ)
34,2023-12-02 19:00:00,23:29:43.6,13:25:13,1.809,2.31,107.8,24.0,12.9,29.10,76.0,308,-22,-41,0.73,131,70,0,49.2,602,602 Marianna (A906 DJ)
35,2023-12-02 20:00:00,23:29:45.5,13:25:20,1.809,2.31,107.8,24.0,12.9,29.33,76.0,321,-30,-29,0.72,131,74,0,49.2,602,602 Marianna (A906 DJ)
36,2023-12-02 21:00:00,23:29:47.5,13:25:27,1.810,2.31,107.8,24.0,12.9,29.49,75.9,337,-36,-17,0.72,132,69,0,49.2,602,602 Marianna (A906 DJ)
37,2023-12-02 22:00:00,23:29:49.4,13:25:34,1.810,2.31,107.7,24.0,13.0,29.60,75.8,355,-39,-6,0.71,132,59,0,49.2,602,602 Marianna (A906 DJ)
38,2023-12-02 23:00:00,23:29:51.4,13:25:42,1.811,2.31,107.7,24.0,13.0,29.63,75.7,14,-38,5,0.71,133,48,0,49.3,602,602 Marianna (A906 DJ)
39,2023-12-03 00:00:00,23:29:53.4,13:25:49,1.811,2.31,107.7,24.0,13.0,29.61,75.5,31,-34,14,0.71,133,36,0,49.3,602,602 Marianna (A906 DJ)
40,2023-12-03 01:00:00,23:29:55.3,13:25:56,1.812,2.31,107.6,24.0,13.0,29.51,75.4,46,-26,22,0.70,134,25,0,49.2,602,602 Marianna (A906 DJ)
41,2023-12-03 02:00:00,23:29:57.3,13:26:04,1.812,2.31,107.6,24.0,13.0,29.37,75.2,58,-17,28,0.70,134,13,0,49.2,602,602 Marianna (A906 DJ)
42,2023-12-03 03:00:00,23:29:59.2,13:26:12,1.813,2.31,107.6,24.0,13.0,29.19,75.0,68,-6,31,0.70,135,2,0,49.3,602,602 Marianna (A906 DJ)
43,2023-12-03 04:00:00,23:30:01.1,13:26:19,1.813,2.31,107.5,24.0,13.0,28.97,74.8,77,5,30,0.69,135,-8,0,49.3,602,602 Marianna (A906 DJ)
44,2023-12-03 05:00:00,23:30:03.0,13:26:27,1.814,2.31,107.5,24.0,13.0,28.76,74.7,86,17,26,0.69,135,-17,0,49.3,602,602 Marianna (A906 DJ)
45,2023-12-03 06:00:00,23:30:04.9,13:26:34,1.814,2.31,107.5,24.0,13.0,28.55,74.6,95,29,20,0.69,136,-25,0,49.3,602,602 Marianna (A906 DJ)
46,2023-12-03 07:00:00,23:30:06.8,13:26:42,1.815,2.31,107.4,24.0,13.0,28.36,74.5,105,41,11,0.68,136,-31,0,49.3,602,602 Marianna (A906 DJ)
47,2023-12-03 08:00:00,23:30:08.7,13:26:49,1.815,2.31,107.4,24.0,13.0,28.22,74.5,119,52,2,0.68,137,-33,0,49.2,602,602 Marianna (A906 DJ)
48,2023-12-03 09:00:00,23:30:10.6,13:26:57,1.816,2.31,107.4,24.0,13.0,28.13,74.6,140,61,-9,0.67,137,-33,0,49.3,602,602 Marianna (A906 DJ)

### (과제)

df에 있는 소행성 목록들의 eph를 csv 파일로 저장해 보자.

In [ ]:
from pathlib import Path
from astroquery.mpc import MPC
from pprint import pprint
import re

for i, row  in df.iterrows():
    print("row['Full name'] :", row["Full name"])

    #asteroid_names = re.findall('\(([^)]+)', df['Full name'][0])   #extracts string in bracket()
    #print (asteroid_names[0])
    asteroid_id = df['Full name'][i].split(" ")[0]   #extracts string
    print(asteroid_id)

    eph = MPC.get_ephemeris(asteroid_id, step='1h', number=30 * 24)
    print(f"Proper motion: {eph['Proper motion'].quantity.to('arcmin/h').max():.03f}")
    eph = MPC.get_ephemeris(asteroid_id, location='P64',
                        ra_format={'sep': ':', 'unit': 'hourangle', 'precision': 1},
                        dec_format={'sep': ':', 'precision': 0},
                        step='1h')
    print("type(eph): ", type(eph))
    #print("eph: ", eph)

    df_eph = eph.to_pandas()
    df_eph['Asteroid ID'] = asteroid_id
    df_eph['Asteroid name'] = df['Full name'][i]
    df_eph.to_csv(str(BASEPATH/save_dir_name/ f"eph_asteroid_{asteroid_id}.csv"))

row['Full name'] : 602 Marianna (A906 DJ)
602
Proper motion: 0.819 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 678 Fredegundis (A909 BQ)
678
Proper motion: 0.911 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 639 Latona (A907 OA)
639
Proper motion: 0.390 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 123 Brunhild (A872 OB)
123
Proper motion: 0.437 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 135 Hertha (A874 DA)
135
Proper motion: 0.500 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 122 Gerda (A872 OA)
122
Proper motion: 0.227 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 127 Johanna (A872 VB)
127
Proper motion: 0.294 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 509 Iolanda (A903 HD)
509
Proper motion: 0.308 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 21 Lutetia (A852 VA)
21
Proper motion: 0.305 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 93 Minerva (A867 QA)
93
Proper motion: 0.413 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 119 Althaea (A872 GA)
119
Proper motion: 0.356 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 132 Aethra (A873 LA)
132
Proper motion: 0.844 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 139 Juewa (A874 TA)
139
Proper motion: 0.517 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 241 Germania (A884 RA)
241
Proper motion: 0.453 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 409 Aspasia (A895 XC)
409
Proper motion: 0.544 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 154 Bertha (A875 VD)
154
Proper motion: 0.496 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 144 Vibilia (A875 LA)
144
Proper motion: 0.479 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 895 Helio (A918 NA)
895
Proper motion: 0.684 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 363 Padua (A893 FD)
363
Proper motion: 0.548 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 481 Emita (A902 CB)
481
Proper motion: 0.587 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 182 Elsa (A878 CC)
182
Proper motion: 0.541 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 24 Themis (A853 GA)
24
Proper motion: 0.503 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 70 Panopaea (A861 JA)
70
Proper motion: 0.613 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 503 Evelyn (A903 BL)
503
Proper motion: 0.583 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 113 Amalthea (A871 EA)
113
Proper motion: 0.633 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 65 Cybele (A861 EB)
65
Proper motion: 0.454 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 306 Unitas (A891 EA)
306
Proper motion: 0.642 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 346 Hermentaria (A892 WC)
346
Proper motion: 0.587 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 358 Apollonia (A893 EC)
358
Proper motion: 0.549 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 347 Pariana (A892 WD)
347
Proper motion: 0.647 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 95 Arethusa (A867 WA)
95
Proper motion: 0.598 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 758 Mancunia (A912 KB)
758
Proper motion: 0.524 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 480 Hansa (A901 KB)
480
Proper motion: 0.751 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 317 Roxane (A891 RD)
317
Proper motion: 0.673 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 160 Una (A876 DA)
160
Proper motion: 0.581 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 498 Tokio (A902 XA)
498
Proper motion: 0.648 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 210 Isabella (A879 VA)
210
Proper motion: 0.588 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 389 Industria (A894 EE)
389
Proper motion: 0.620 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 159 Aemilia (A876 BA)
159
Proper motion: 0.532 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 149 Medusa (A875 SA)
149
Proper motion: 0.690 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 407 Arachne (A895 TB)
407
Proper motion: 0.618 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 704 Interamnia (A910 TC)
704
Proper motion: 0.622 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 488 Kreusa (A902 MC)
488
Proper motion: 0.562 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 37 Fides (A855 TB)
37
Proper motion: 0.583 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 776 Berbericia (A914 BE)
776
Proper motion: 0.675 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 4 Vesta (A807 FA)
4
Proper motion: 0.669 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 9 Metis (A848 HA)
9
Proper motion: 0.655 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 48 Doris (A857 SA)
48
Proper motion: 0.523 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 5 Astraea (A845 XA)
5
Proper motion: 0.616 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 72 Feronia (A861 KA)
72
Proper motion: 0.679 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 804 Hispania (A915 FK)
804
Proper motion: 0.553 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 92 Undina (A867 NA)
92
Proper motion: 0.507 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 128 Nemesis (A872 WA)
128
Proper motion: 0.466 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 71 Niobe (A861 PA)
71
Proper motion: 0.498 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 78 Diana (A863 EA)
78
Proper motion: 0.417 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 38 Leda (A856 AA)
38
Proper motion: 0.454 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 118 Peitho (A872 EA)
118
Proper motion: 0.579 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 451 Patientia (A899 XA)
451
Proper motion: 0.366 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 192 Nausikaa (A879 DA)
192
Proper motion: 0.346 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 63 Ausonia (A861 CA)
63
Proper motion: 0.465 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 372 Palma (A893 QB)
372
Proper motion: 0.488 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 349 Dembowska (A892 XB)
349
Proper motion: 0.468 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 31 Euphrosyne (A854 RA)
31
Proper motion: 0.613 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 23 Thalia (A852 XA)
23
Proper motion: 1.020 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>

저장

In [ ]:
eph = MPC.get_ephemeris('A894 VC', start='1996-03-01', step='1h', number=30 * 24)
print(eph['Proper motion'].quantity.to('deg/h').max())
eph = MPC.get_ephemeris('A894 VC', location='P64',
                        ra_format={'sep': ':', 'unit': 'hourangle', 'precision': 1},
                        dec_format={'sep': ':', 'precision': 0},
                        step='1h')
print(eph)

0.023877777777777776 deg / h
          Date              RA       Dec    ... Uncertainty 3sig Unc. P.A.
                        hourangle    deg    ...      arcsec         deg
----------------------- ---------- -------- ... ---------------- ---------
2023-12-01 09:00:00.000 21:23:21.4 -4:53:29 ...                0      77.0
2023-12-01 10:00:00.000 21:23:26.6 -4:53:22 ...                0      77.0
2023-12-01 11:00:00.000 21:23:31.7 -4:53:15 ...                0      77.0
2023-12-01 12:00:00.000 21:23:36.9 -4:53:08 ...                0      77.0
2023-12-01 13:00:00.000 21:23:42.1 -4:53:01 ...                0      77.0
2023-12-01 14:00:00.000 21:23:47.3 -4:52:54 ...                0      77.0
2023-12-01 15:00:00.000 21:23:52.5 -4:52:47 ...                0      77.1
2023-12-01 16:00:00.000 21:23:57.7 -4:52:40 ...                0      77.0
2023-12-01 17:00:00.000 21:24:03.0 -4:52:32 ...                0      77.1
2023-12-01 18:00:00.000 21:24:08.2 -4:52:25 ...                0      77.0
                    ...        ...      ... ...              ...       ...
2023-12-03 00:00:00.000 21:26:44.9 -4:48:46 ...                0      77.0
2023-12-03 01:00:00.000 21:26:50.2 -4:48:38 ...                0      77.0
2023-12-03 02:00:00.000 21:26:55.4 -4:48:31 ...                0      77.0
2023-12-03 03:00:00.000 21:27:00.6 -4:48:23 ...                0      77.0
2023-12-03 04:00:00.000 21:27:05.8 -4:48:16 ...                0      77.0
2023-12-03 05:00:00.000 21:27:11.0 -4:48:08 ...                0      77.0
2023-12-03 06:00:00.000 21:27:16.2 -4:48:01 ...                0      77.0
2023-12-03 07:00:00.000 21:27:21.3 -4:47:53 ...                0      76.9
2023-12-03 08:00:00.000 21:27:26.5 -4:47:45 ...                0      76.9
2023-12-03 09:00:00.000 21:27:31.6 -4:47:38 ...                0      76.9
Length = 49 rows