# 소행성 관측 계획 수립하기

* 이 노트북을 구글 코랩에서 실행하고자 한다면 [파일] - [드라이브에 사본 저장]을 하여 본인의 소유로 만든 후에 코드를 실행하거나 수정할 수 있습니다.

* 이 파일은 실제 수업에 사용하므로 필요에 따라 예고 없이 변경될 수 있습니다.

* If you have any questions or comments on this document, please email me(Kiehyun.Park@gmail.com).

* 이 파일(문서)는 공교육 현장에서 수업시간에 자유롭게 사용할 수 있으나, 다른 목적으로 사용할 시에는 사전에 연락을 주셔서 상의해 주시기 바랍니다.

이 자료는 What's observable로 부터 특정한 날 관측할 수 있는 소행성의 목록을 만드는 과정을 설명합니다.

## 필요한 환경

이 프로젝트를 위해서는 아래의 모듈이 필요합니다.

> numpy, pandas, matplotlib, astroquery, requests, astropy, astropy.units, certifi, version_information

### 구글 코랩에 한글 폰트 설치

matplotlib에서 한글을 사용하기 위해서는 한글 폰트가 필요하다. 구글 코랩에서 현재의 Jupyter notebook을 실행한다면 아래 코드를 실행 한 후 런타임 다시 시작을 해 줘야 한글을 사용할 수 있을 것이다.

In [1]:
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf

'sudo'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
'sudo'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
'rm'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.

### 런타임 다시 시작

위의 셀을 실행한 다음 반드시 다음 과정을 잊지 말자.

* [메뉴]-[런타임]-[런터임 다시 시작]

* [메뉴]-[런타임]-[이전 셀 실행]을 해주어야 한다.

### 한글 폰트 사용

위에서 한글 폰트를 설치하고, 런타임 다시시작을 했다면 구글 코랩에서 폰트 경로를 설정하여 한글 사용이 가능해 진다.

In [2]:
#visualization
import matplotlib as mpl
import matplotlib.pylab as plb
import matplotlib.pyplot as plt

# 브라우저에서 바로 그려지도록
%matplotlib inline

# 그래프에 retina display 적용
%config InlineBackend.figure_format = 'retina'

# Colab 의 한글 폰트 설정
plt.rc('font', family='NanumBarunGothic')

# 유니코드에서  음수 부호설정
mpl.rc('axes', unicode_minus=False)

### 모듈 설치 및 버전 확인

아래 셀을 실행하면 이 노트북을 실행하는데 필요한 모듈을 설치하고 파이썬 및 관련 모듈의 버전을 확인할 수 있다.

In [3]:
import importlib, sys, subprocess
packages = "numpy, pandas, matplotlib, astroquery, requests, astropy, astropy.units, certifi, version_information" # required modules
pkgs = packages.split(", ")
for pkg in pkgs :
    if not importlib.util.find_spec(pkg):
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg, '-q'])
        print(f"**** {pkg} module is now installed.")
    else:
        print(f"******** {pkg} module is already installed.")
%load_ext version_information
import time
now = time.strftime("%Y-%m-%d %H:%M:%S (%Z = GMT%z)")
print(f"This notebook was generated at {now} ")

vv = %version_information {packages}
for i, pkg in enumerate(vv.packages):
    print(f"{i} {pkg[0]:10s} {pkg[1]:s}")

******** numpy module is already installed.
******** pandas module is already installed.
******** matplotlib module is already installed.
******** astroquery module is already installed.
******** requests module is already installed.
******** astropy module is already installed.
******** astropy.units module is already installed.
******** certifi module is already installed.
******** version_information module is already installed.
This notebook was generated at 2023-11-13 20:12:16 (대한민국 표준시 = GMT+0900)
0 Python     3.11.5 64bit [MSC v.1916 64 bit (AMD64)]
1 IPython    8.15.0
2 OS         Windows 10 10.0.22631 SP0
3 numpy      1.26.0
4 pandas     2.0.3
5 matplotlib 3.7.2
6 astroquery 0.4.6
7 requests   2.31.0
8 astropy    5.1
9 astropy.units The 'astropy.units' distribution was not found and is required by the application
10 certifi    2023.07.22
11 version_information 1.0.4

## 날짜와 시간 다루기

### datetime.datetime

Python 내장 모듈인 datetime을 사용하면 날짜와 시각 객체를 다룰 수 있습니다.

#### 표준시와 세계시

In [4]:
from datetime import datetime, timedelta, timezone

dt_kst_now = datetime.now()
print("현재 시각(KST=GMT+9) :", dt_kst_now)

timezone_utc = timezone(timedelta(hours=-9))
dt_utc_now = dt_kst_now.astimezone(timezone_utc)
print("현재 시각(UTC) :", dt_utc_now)

현재 시각(KST=GMT+9) : 2023-11-13 20:12:17.755207
현재 시각(UTC) : 2023-11-13 02:12:17.755207-09:00

#### fits header의 시간 형식

fits header의 시간 형식은 '2023-09-11T20:19:18'의 형태를 띠고 있는데 datetime.strptime을 이용하면 날짜시간 형식을 바로 datetime 객체로 만들 수 있습니다.

이를 세계시로 바꾸려면 timedelta를 이용할 수 있습니다.

In [5]:
start_dt_kst_str = '2023-09-11T20:19:18'
end_dt_kst_str = '2023-12-31T00:00:00'

start_dt_kst = datetime.strptime(start_dt_kst_str, '%Y-%m-%dT%H:%M:%S')
print(start_dt_kst)
print(type(start_dt_kst))

start_dt_utc = start_dt_kst + timedelta(hours=-9)
print(start_dt_utc)
print(type(start_dt_utc))

2023-09-11 20:19:18
<class 'datetime.datetime'>
2023-09-11 11:19:18
<class 'datetime.datetime'>

#### string 형태로 변환하기

datetime 객체를 string으로 바꿀때는 strftime 메쏘들ㄹ 이용하면 됩니다.

In [6]:

start_dt_utc_str = start_dt_utc.strftime('%Y-%m-%dT%H:%M:%S')
print("start_dt_utc_str :", start_dt_utc_str)
print("type(start_dt_utc_str) :", type(start_dt_utc_str))

start_dt_utc_str : 2023-09-11T11:19:18
type(start_dt_utc_str) : <class 'str'>

#### datetime 이용하여 list 생성

아래와 같이 하면, 시작 시각과 끝나는 시각, 그리고 시간 간격을 정해 주고, Python의 datatime 객체를 이용하여 일정 시간 간격의 목록(list)을 만을 수 있다.

In [7]:
from datetime import datetime, timedelta
start_time_text = "2017-01-01"
end_time_text = "2017-06-01"
dt = 1
def datetime_range(start_dt, end_dt, delta):
    '''
        Parameters
        ----------
        start_dt : datetime.datetime
        end_dt : datetime.datetime
        delta : int
    '''
    current = start_dt
    while current < end_dt:
        yield current
        current += delta

dts = [dt.strftime('%Y-%m-%d') for dt in
            datetime_range(datetime.fromisoformat(start_time_text), datetime.fromisoformat(end_time_text),
            timedelta(days=dt))]

print("len(dts):", len(dts))
print("dts", dts)

len(dts): 151
dts ['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08', '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12', '2017-01-13', '2017-01-14', '2017-01-15', '2017-01-16', '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20', '2017-01-21', '2017-01-22', '2017-01-23', '2017-01-24', '2017-01-25', '2017-01-26', '2017-01-27', '2017-01-28', '2017-01-29', '2017-01-30', '2017-01-31', '2017-02-01', '2017-02-02', '2017-02-03', '2017-02-04', '2017-02-05', '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09', '2017-02-10', '2017-02-11', '2017-02-12', '2017-02-13', '2017-02-14', '2017-02-15', '2017-02-16', '2017-02-17', '2017-02-18', '2017-02-19', '2017-02-20', '2017-02-21', '2017-02-22', '2017-02-23', '2017-02-24', '2017-02-25', '2017-02-26', '2017-02-27', '2017-02-28', '2017-03-01', '2017-03-02', '2017-03-03', '2017-03-04', '2017-03-05', '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09', '2017-03-10', '2017-03-11', '2017-03-12', '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-17', '2017-03-18', '2017-03-19', '2017-03-20', '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24', '2017-03-25', '2017-03-26', '2017-03-27', '2017-03-28', '2017-03-29', '2017-03-30', '2017-03-31', '2017-04-01', '2017-04-02', '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06', '2017-04-07', '2017-04-08', '2017-04-09', '2017-04-10', '2017-04-11', '2017-04-12', '2017-04-13', '2017-04-14', '2017-04-15', '2017-04-16', '2017-04-17', '2017-04-18', '2017-04-19', '2017-04-20', '2017-04-21', '2017-04-22', '2017-04-23', '2017-04-24', '2017-04-25', '2017-04-26', '2017-04-27', '2017-04-28', '2017-04-29', '2017-04-30', '2017-05-01', '2017-05-02', '2017-05-03', '2017-05-04', '2017-05-05', '2017-05-06', '2017-05-07', '2017-05-08', '2017-05-09', '2017-05-10', '2017-05-11', '2017-05-12', '2017-05-13', '2017-05-14', '2017-05-15', '2017-05-16', '2017-05-17', '2017-05-18', '2017-05-19', '2017-05-20', '2017-05-21', '2017-05-22', '2017-05-23', '2017-05-24', '2017-05-25', '2017-05-26', '2017-05-27', '2017-05-28', '2017-05-29', '2017-05-30', '2017-05-31']

### astropy.time

표준시나 세계시 정도는 datetime을 사용해도 무방하지만 천문학에서 사용하는 시간에는 조금 부족합니다. 천문학에서 사용하는 시간계는 datetime 모듈보다는 astropy.time 모듈을 사용하기를 권장합니다.

#### 세계시

In [8]:
from astropy.time import Time

t_kst_now = Time.now()
print("현재 시각(KST=GMT+9) :", t_kst_now)

t_ut_now = Time(datetime.utcnow(), scale='utc', location=('127d', '37d'))
print("현재 시각(UTC) :", t_ut_now)

print("type(t_ut_now) ;", type(t_ut_now))

현재 시각(KST=GMT+9) : 2023-11-13 11:12:17.826016

현재 시각(UTC) : 2023-11-13 11:12:17.828049
type(t_ut_now) ; <class 'astropy.time.core.Time'>

#### dir함수로 메쏘드 알아보기

In [9]:
print("dir(t_ut_now) ;", dir(t_ut_now))

dir(t_ut_now) ; ['FORMATS', 'SCALES', 'T', '_APPLICABLE_FUNCTIONS', '_METHOD_FUNCTIONS', '__abstractmethods__', '__add__', '__array_function__', '__array_priority__', '__bool__', '__class__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__weakref__', '_abc_impl', '_advanced_index', '_apply', '_astropy_column_attrs', '_call_erfa', '_format', '_get_delta_tdb_tt', '_get_delta_ut1_utc', '_get_time_fmt', '_init_from_vals', '_make_value_equivalent', '_match_shape', '_set_delta_tdb_tt', '_set_delta_ut1_utc', '_set_scale', '_shaped_like_input', '_sid_time_or_earth_rot_ang', '_time', '_time_comparison', 'argmax', 'argmin', 'argsort', 'byear', 'byear_str', 'cache', 'copy', 'cxcsec', 'datetime', 'datetime64', 'decimalyear', 'delta_tdb_tt', 'delta_ut1_utc', 'diagonal', 'earth_rotation_angle', 'fits', 'flatten', 'format', 'get_delta_ut1_utc', 'gps', 'in_subfmt', 'info', 'insert', 'isclose', 'iso', 'isot', 'isscalar', 'jd', 'jd1', 'jd2', 'jyear', 'jyear_str', 'light_travel_time', 'location', 'mask', 'masked', 'max', 'min', 'mjd', 'ndim', 'now', 'out_subfmt', 'plot_date', 'precision', 'ptp', 'ravel', 'replicate', 'reshape', 'scale', 'shape', 'sidereal_time', 'size', 'sort', 'squeeze', 'stardate', 'strftime', 'strptime', 'swapaxes', 'tai', 'take', 'tcb', 'tcg', 'tdb', 'to_datetime', 'to_value', 'transpose', 'tt', 'unix', 'unix_tai', 'ut1', 'utc', 'value', 'writeable', 'yday', 'ymdhms']

#### Julian day 구하기

In [10]:
print("t_ut_now.to_value(format='jd') ;", t_ut_now.to_value(format='jd'))

t_ut_now.to_value(format='jd') ; 2460261.9668730097

#### 항성시

In [11]:
print("t_ut_now.sidereal_time('mean') :", t_ut_now.sidereal_time('mean'))

t_ut_now.sidereal_time('mean') : 23h09m33.69446851s

#### astropy.time 이용하여 list 생성

일정 시간 간격으로 시뮬레이션 하려면 시간 간격의 리스트를 미리 만들어 두면 편리할 것입니다. 다음은 Python의 astropy.time을 이용하여 일정 시간 간격의 목록(list)을 만드는 방법입니다.

In [12]:
import numpy as np
from astropy.time import Time, TimeDelta

start_time_text = "2023-10-06"
end_time_text = "2023-10-15"
dt = 1

def astropyTime_range(start_t, end_t, delta):
    '''
        Parameters
        ----------
        start_t : datetime.datetime
        end_t : datetime.datetime
        delta : int
    '''
    current = start_t
    while current < end_t:
        yield current
        current += delta

dts = [dt for dt in
        astropyTime_range(Time(start_time_text), Time(end_time_text),
        TimeDelta(dt, format='jd'))]

print(len(dts))
print(dts)

9
[<Time object: scale='utc' format='iso' value=2023-10-06 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-07 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-08 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-09 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-10 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-11 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-12 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-13 00:00:00.000>, <Time object: scale='utc' format='iso' value=2023-10-14 00:00:00.000>]

## What's observable

[What's observable](https://ssd.jpl.nasa.gov/tools/sbwobs.html) 에서는 관측소 코드와 관측 조건들을 설정하여 소행성과 혜성의 관측 대상의 정보를 얻을 수 있습니다.

### Horizons API

[Horizons API](https://ssd-api.jpl.nasa.gov/doc/horizons.html)를 제공하고 있어 requests로 받아아올 url을 만들수 있습니다.

#### 검색 조건 설정

먼저 조건들을 변수로 설정해 보겠습니다.

In [13]:
#############################################
# variables
mpc_code='P64' # Observer Location: GSHS Observatory, Suwon [code: P64]

#관측 시각 설정 (현재 시각)
t_ut_now = Time(datetime.utcnow(), scale='utc', location=('127d', '37d'))
print("type(obs_dt_utc) :", type(t_ut_now))
print("현재 시각(UTC) :", t_ut_now)

#관측 시각 설정 (임의의 시각)
# t_ut_now = Time(datetime(2023, 10, 2, 10, 0, 0), scale='utc', location=('127d', '37d'))
# print("type(obs_dt_utc) :", type(t_ut_now))
# print("현재 시각(UTC) :", t_ut_now)

obs_datetime = t_ut_now.strftime('%Y-%m-%d %H:%M:%S')
print("obs_datetime :", obs_datetime)
obs_date = t_ut_now.strftime('%Y%m%d')
print("obs_date :", obs_date)

elev_min=60  #
time_min=15
vmag_min=6
vmag_max=13
list_num=100
sort='trans'

type(obs_dt_utc) : <class 'astropy.time.core.Time'>
현재 시각(UTC) : 2023-11-13 11:12:40.310594
obs_datetime : 2023-11-13 11:12:40
obs_date : 20231113

#### url 만들기

In [14]:
# Define API URL and SPK filename:
url = 'https://ssd-api.jpl.nasa.gov/sbwobs.api'
spk_filename = 'spk_file.bsp'

# Get the requested SPK-ID from the command-line:
if (len(sys.argv)) == 1:
  print("please specify SPK-ID on the command-line")
  sys.exit(2)
spkid = sys.argv[1]

# Build the appropriate URL for this API request:
# IMPORTANT: You must encode the "=" as "%3D" and the ";" as "%3B" in the
#            Horizons COMMAND parameter specification.
url += f"?sb-kind=a&mpc-code={mpc_code}&obs-time={str(obs_datetime)}&elev-min={elev_min}&time-min={time_min}"
url += f"&vmag-max={vmag_max}&vmag-min={vmag_min}&optical=true&fmt-ra-dec=true&mag-required=true&output-sort={sort}&maxoutput={list_num}"

print("url :", url)

url : https://ssd-api.jpl.nasa.gov/sbwobs.api?sb-kind=a&mpc-code=P64&obs-time=2023-11-13 11:12:40&elev-min=60&time-min=15&vmag-max=13&vmag-min=6&optical=true&fmt-ra-dec=true&mag-required=true&output-sort=trans&maxoutput=100

### reauests.get

api에서 제공하는 내용을 json 형태로 받아 보겠습니다.

In [15]:
import json
import requests
# Submit the API request and decode the JSON-response:
response = requests.get(url)
try:
  data = json.loads(response.text)
  print(data)
except ValueError:
  print("Unable to decode JSON results")

{'signature': {'source': 'NASA/JPL Small-Body Observability API', 'version': '1.0'}, 'obs_constraints': {'optical': 'true', 'vmag-min': '6', 'elev-min': '60', 'vmag-max': '13', 'output-sort': 'trans', 'obs-time': '2023-11-13 11:12:40', 'mag-required': 'true', 'maxoutput': '100', 'time-min': '15', 'mpc-code': 'P64', 'fmt-ra-dec': 'true'}, 'sb_constraints': {'sb-kind': 'a'}, 'location': 'GSHS Observatory, Suwon', 'obs_night': {'sun_set_az': '248.4', 'sun_set': '2023-11-12 08:23', 'end_civil': '2023-11-12 08:51', 'end_nautical': '2023-11-12 09:22', 'end_astronomical': '2023-11-12 09:53', 'begin_astronomical': '2023-11-12 20:36', 'begin_nautical': '2023-11-12 21:07', 'begin_civil': '2023-11-12 21:39', 'sun_rise_az': '111.8', 'sun_rise': '2023-11-12 22:06', 'transit_phase': '0.00', 'transit': '1984-10-26 23:58 ', 'moon_set_phase': '0.01', 'moon_set': '2023-11-12 07:35 ', 'moon_rise_phase': '0.00', 'moon_rise': '2023-11-12 21:46 ', 'begin_dark': '2023-11-12 09:53', 'mid_dark': '2023-11-12 15:14', 'end_dark': '2023-11-12 20:36', 'dark_time': '10:43'}, 'fields': ['Designation', 'Full name', 'Rise time', 'Transit time', 'Set time', 'Max. time observable', 'R.A.', 'Dec.', 'Vmag', 'Helio. range (au)', 'Topo.range (au)', 'Object-Observer-Sun (deg)', 'Object-Observer-Moon (deg)', 'Galactic latitude (deg)'], 'sort_by': 'transit time (asc.)', 'data': [['602', '602 Marianna (A906 DJ)', '10:09', '11:27', '12:46', '02:36', '23:20:57', '+12 58\'53"', '12.6', '2.31', '1.59', '124.75', '134.0', '-44.25'], ['678', '678 Fredegundis (A909 BQ)', '11:04', '12:01', '12:58', '01:54', '23:55:00', '+10 14\'50"', '12.4', '2.02', '1.22', '132.21', '141.5', '-50.22'], ['120', '120 Lachesis (A872 GB)', '11:41', '13:03', '14:24', '02:43', '00:56:50', '+13 30\'38"', '13.0', '3.28', '2.40', '147.67', '157.0', '-49.48'], ['639', '639 Latona (A907 OA)', '11:24', '13:17', '15:11', '03:47', '01:11:31', '+20 21\'26"', '12.6', '2.76', '1.85', '151.88', '160.8', '-42.43'], ['123', '123 Brunhild (A872 OB)', '11:36', '13:28', '15:20', '03:44', '01:22:14', '+19 55\'02"', '12.5', '2.42', '1.49', '154.40', '163.3', '-42.54'], ['135', '135 Hertha (A874 DA)', '12:17', '13:33', '14:49', '02:31', '01:27:15', '+12 34\'47"', '11.3', '2.18', '1.25', '154.67', '164.0', '-49.54'], ['122', '122 Gerda (A872 OA)', '13:02', '13:45', '14:28', '01:26', '01:39:40', '+08 56\'25"', '12.6', '3.25', '2.32', '156.33', '165.2', '-52.29'], ['127', '127 Johanna (A872 VB)', '12:42', '14:10', '15:39', '02:56', '02:04:45', '+14 38\'08"', '12.5', '2.73', '1.76', '164.01', '173.3', '-44.83'], ['509', '509 Iolanda (A903 HD)', '12:58', '14:10', '15:23', '02:24', '02:04:33', '+12 05\'15"', '12.4', '2.79', '1.83', '163.19', '172.1', '-47.19'], ['595', '595 Polyxena (A906 FL)', '12:19', '14:17', '16:14', '03:55', '02:10:56', '+21 30\'34"', '12.7', '3.23', '2.26', '165.56', '173.2', '-37.92'], ['21', '21 Lutetia (A852 VA)', '13:28', '14:33', '15:37', '02:08', '02:27:00', '+11 02\'05"', '10.3', '2.25', '1.28', '167.60', '174.2', '-45.61'], ['93', '93 Minerva (A867 QA)', '12:39', '14:48', '16:56', '04:16', '02:41:57', '+24 54\'22"', '12.1', '2.96', '1.98', '170.28', '171.4', '-31.79'], ['119', '119 Althaea (A872 GA)', '13:37', '14:49', '16:01', '02:24', '02:43:11', '+12 03\'00"', '11.4', '2.40', '1.41', '171.36', '174.5', '-42.62'], ['132', '132 Aethra (A873 LA)', '12:31', '15:03', '17:34', '05:03', '02:57:10', '+37 18\'21"', '12.4', '2.46', '1.51', '160.22', '158.6', '-19.36'], ['139', '139 Juewa (A874 TA)', '12:59', '15:22', '17:46', '04:46', '03:16:57', '+31 29\'40"', '12.3', '2.92', '1.95', '166.16', '161.9', '-22.14'], ['241', '241 Germania (A884 RA)', '13:18', '15:23', '17:27', '04:09', '03:17:09', '+23 36\'53"', '11.7', '2.87', '1.89', '173.90', '167.2', '-28.52'], ['409', '409 Aspasia (A895 XC)', '13:26', '15:24', '17:22', '03:56', '03:18:23', '+21 38\'41"', '11.3', '2.76', '1.77', '175.64', '167.8', '-29.92'], ['154', '154 Bertha (A875 VD)', '13:12', '15:28', '17:44', '04:31', '03:22:40', '+27 51\'17"', '12.6', '3.40', '2.42', '169.48', '163.7', '-24.38'], ['90', '90 Antiope (A866 TA)', '13:49', '15:32', '17:16', '03:27', '03:26:46', '+17 46\'50"', '12.8', '3.13', '2.14', '176.04', '166.7', '-31.67'], ['144', '144 Vibilia (A875 LA)', '14:07', '15:40', '17:12', '03:05', '03:34:11', '+15 29\'14"', '10.4', '2.13', '1.14', '173.82', '164.8', '-32.19'], ['895', '895 Helio (A918 NA)', '13:12', '15:46', '18:19', '05:06', '03:40:15', '+39 21\'55"', '12.5', '2.78', '1.84', '157.40', '152.8', '-12.99'], ['363', '363 Padua (A893 FD)', '14:13', '16:02', '17:51', '03:37', '03:56:46', '+19 03\'12"', '12.7', '2.63', '1.65', '168.86', '159.5', '-25.88'], ['481', '481 Emita (A902 CB)', '14:22', '16:03', '17:44', '03:22', '03:58:02', '+17 11\'49"', '11.7', '2.31', '1.33', '168.57', '159.3', '-26.95'], ['182', '182 Elsa (A878 CC)', '14:23', '16:04', '17:46', '03:23', '03:59:03', '+17 19\'19"', '11.1', '1.96', '0.985', '168.33', '159.0', '-26.69'], ['24', '24 Themis (A853 GA)', '14:11', '16:08', '18:04', '03:52', '04:02:21', '+21 06\'09"', '11.7', '3.08', '2.11', '167.24', '158.0', '-23.51'], ['70', '70 Panopaea (A861 JA)', '14:09', '16:17', '18:26', '04:16', '04:11:55', '+24 58\'01"', '12.2', '2.75', '1.79', '163.92', '155.1', '-19.24'], ['503', '503 Evelyn (A903 BL)', '14:26', '16:17', '18:08', '03:41', '04:11:34', '+19 31\'38"', '12.5', '2.39', '1.42', '165.34', '156.0', '-23.02'], ['65', '65 Cybele (A861 EB)', '14:44', '16:22', '18:00', '03:15', '04:16:46', '+16 30\'21"', '12.5', '3.82', '2.86', '164.04', '154.7', '-24.09'], ['113', '113 Amalthea (A871 EA)', '14:59', '16:23', '17:48', '02:48', '04:18:03', '+13 54\'51"', '12.0', '2.54', '1.57', '163.23', '154.1', '-25.53'], ['346', '346 Hermentaria (A892 WC)', '15:07', '16:34', '18:01', '02:53', '04:28:45', '+14 23\'29"', '11.0', '2.56', '1.60', '160.83', '151.6', '-23.21'], ['306', '306 Unitas (A891 EA)', '15:42', '16:35', '17:28', '01:45', '04:29:59', '+09 48\'15"', '12.2', '2.43', '1.48', '159.07', '150.3', '-25.76'], ['358', '358 Apollonia (A893 EC)', '15:04', '16:42', '18:20', '03:15', '04:36:41', '+16 32\'33"', '12.6', '2.44', '1.49', '159.30', '150.0', '-20.38'], ['95', '95 Arethusa (A867 WA)', '14:47', '16:46', '18:46', '03:59', '04:40:59', '+22 01\'54"', '11.8', '2.64', '1.69', '158.24', '149.0', '-16.17'], ['347', '347 Pariana (A892 WD)', '15:15', '16:46', '18:17', '03:02', '04:40:47', '+15 12\'43"', '13.0', '2.70', '1.75', '158.14', '148.9', '-20.40'], ['758', '758 Mancunia (A912 KB)', '15:12', '16:49', '18:27', '03:15', '04:43:59', '+16 26\'31"', '12.4', '2.72', '1.78', '157.55', '148.2', '-19.05'], ['480', '480 Hansa (A901 KB)', '15:11', '16:56', '18:41', '03:29', '04:50:51', '+18 04\'26"', '11.9', '2.54', '1.60', '156.06', '146.7', '-16.76'], ['317', '317 Roxane (A891 RD)', '15:22', '17:14', '19:06', '03:44', '05:08:44', '+19 56\'06"', '12.9', '2.26', '1.34', '151.89', '142.6', '-12.24'], ['160', '160 Una (A876 DA)', '15:09', '17:26', '19:43', '04:33', '05:20:45', '+28 17\'29"', '13.0', '2.55', '1.65', '148.27', '139.4', '-5.22'], ['498', '498 Tokio (A902 XA)', '15:57', '17:34', '19:12', '03:15', '05:29:13', '+16 30\'21"', '12.7', '2.53', '1.64', '146.79', '137.5', '-10.08'], ['389', '389 Industria (A894 EE)', '15:20', '17:39', '19:58', '04:38', '05:33:58', '+29 23\'42"', '12.2', '2.68', '1.81', '145.21', '136.4', '-2.20'], ['159', '159 Aemilia (A876 BA)', '16:19', '17:54', '19:29', '03:09', '05:49:02', '+15 55\'21"', '12.9', '2.84', '1.99', '142.00', '132.7', '-6.32'], ['704', '704 Interamnia (A910 TC)', '15:50', '18:15', '20:41*', '04:46', '06:10:24', '+32 54\'33"', '10.9', '2.78', '1.98', '136.91', '128.3', '6.29'], ['37', '37 Fides (A855 TB)', '16:00', '18:16', '20:32', '04:32', '06:10:46', '+27 59\'49"', '10.6', '2.18', '1.35', '137.40', '128.4', '4.03'], ['488', '488 Kreusa (A902 MC)', '16:15', '18:16', '20:16', '04:01', '06:10:39', '+22 23\'59"', '12.8', '3.01', '2.21', '137.51', '128.3', '1.32'], ['776', '776 Berbericia (A914 BE)', '16:26', '18:29', '20:32', '04:06', '06:23:57', '+23 11\'40"', '11.8', '2.59', '1.80', '134.48', '125.3', '4.40'], ['4', '4 Vesta (A807 FA)', '16:46', '18:35', '20:25', '03:38', '06:30:18', '+19 11\'24"', '7.25', '2.57', '1.80', '132.68', '123.4', '3.87'], ['9', '9 Metis (A848 HA)', '16:31', '18:38', '20:45*', '04:05', '06:32:36', '+24 27\'59"', '9.47', '2.09', '1.29', '132.55', '123.4', '6.74'], ['48', '48 Doris (A857 SA)', '17:22', '18:49', '20:16', '02:53', '06:44:03', '+14 22\'47"', '12.0', '2.91', '2.18', '128.66', '119.3', '4.62'], ['5', '5 Astraea (A845 XA)', '17:19', '18:54', '20:29', '03:10', '06:49:09', '+16 00\'28"', '10.7', '2.27', '1.52', '127.76', '118.4', '6.45'], ['92', '92 Undina (A867 NA)', '17:56', '19:51', '21:46*', '02:40', '07:46:24', '+20 38\'41"', '12.5', '3.33', '2.78', '115.20', '106.0', '20.73'], ['128', '128 Nemesis (A872 WA)', '18:45', '20:45*', '22:45*', '01:51', '08:40:19', '+22 04\'28"', '12.7', '2.68', '2.28', '103.23', '94.18', '33.00'], ['71', '71 Niobe (A861 PA)', '18:39', '21:02*', '23:24*', '01:57', '08:57:02', '+30 58\'26"', '12.3', '2.90', '2.54', '101.73', '93.19', '38.93'], ['78', '78 Diana (A863 EA)', '18:51', '21:03*', '23:14*', '01:45', '08:57:59', '+26 01\'25"', '12.5', '2.12', '1.71', '100.31', '91.49', '38.00'], ['451', '451 Patientia (A899 XA)', '19:46', '21:48*', '23:50*', '00:50', '09:43:24', '+22 41\'21"', '12.3', '2.93', '2.77', '89.44', '80.63', '47.11'], ['192', '192 Nausikaa (A879 DA)', '20:13', '21:58*', '23:43*', '00:23', '09:53:21', '+18 05\'01"', '12.2', '2.42', '2.28', '85.69', '76.70', '47.88'], ['31', '31 Euphrosyne (A854 RA)', '20:17', '22:48*', '01:20*', '00:19', '10:44:10', '+37 42\'15"', '11.9', '2.53', '2.45', '83.43', '76.15', '61.02']], 'total_objects': '56', 'shown_objects': '56'}

안에 들어 있는 데이터를 확인해 보곘습니다.

In [16]:
print("type(data) :", type(data))
print("data.keys :", data.keys)

type(data) : <class 'dict'>
data.keys : <built-in method keys of dict object at 0x00000173BEC97D80>

 아마도 data['fields']에 있는 것이 필요한 자료인것 같습니다.

In [17]:
print(data['obs_constraints'])
print(data['sb_constraints'])
print(data['fields'])
print(data['data'])
print(type(data['fields']))
print(len(data['fields']))
print(len(data['data'][0]))

{'optical': 'true', 'vmag-min': '6', 'elev-min': '60', 'vmag-max': '13', 'output-sort': 'trans', 'obs-time': '2023-11-13 11:12:40', 'mag-required': 'true', 'maxoutput': '100', 'time-min': '15', 'mpc-code': 'P64', 'fmt-ra-dec': 'true'}
{'sb-kind': 'a'}
['Designation', 'Full name', 'Rise time', 'Transit time', 'Set time', 'Max. time observable', 'R.A.', 'Dec.', 'Vmag', 'Helio. range (au)', 'Topo.range (au)', 'Object-Observer-Sun (deg)', 'Object-Observer-Moon (deg)', 'Galactic latitude (deg)']
[['602', '602 Marianna (A906 DJ)', '10:09', '11:27', '12:46', '02:36', '23:20:57', '+12 58\'53"', '12.6', '2.31', '1.59', '124.75', '134.0', '-44.25'], ['678', '678 Fredegundis (A909 BQ)', '11:04', '12:01', '12:58', '01:54', '23:55:00', '+10 14\'50"', '12.4', '2.02', '1.22', '132.21', '141.5', '-50.22'], ['120', '120 Lachesis (A872 GB)', '11:41', '13:03', '14:24', '02:43', '00:56:50', '+13 30\'38"', '13.0', '3.28', '2.40', '147.67', '157.0', '-49.48'], ['639', '639 Latona (A907 OA)', '11:24', '13:17', '15:11', '03:47', '01:11:31', '+20 21\'26"', '12.6', '2.76', '1.85', '151.88', '160.8', '-42.43'], ['123', '123 Brunhild (A872 OB)', '11:36', '13:28', '15:20', '03:44', '01:22:14', '+19 55\'02"', '12.5', '2.42', '1.49', '154.40', '163.3', '-42.54'], ['135', '135 Hertha (A874 DA)', '12:17', '13:33', '14:49', '02:31', '01:27:15', '+12 34\'47"', '11.3', '2.18', '1.25', '154.67', '164.0', '-49.54'], ['122', '122 Gerda (A872 OA)', '13:02', '13:45', '14:28', '01:26', '01:39:40', '+08 56\'25"', '12.6', '3.25', '2.32', '156.33', '165.2', '-52.29'], ['127', '127 Johanna (A872 VB)', '12:42', '14:10', '15:39', '02:56', '02:04:45', '+14 38\'08"', '12.5', '2.73', '1.76', '164.01', '173.3', '-44.83'], ['509', '509 Iolanda (A903 HD)', '12:58', '14:10', '15:23', '02:24', '02:04:33', '+12 05\'15"', '12.4', '2.79', '1.83', '163.19', '172.1', '-47.19'], ['595', '595 Polyxena (A906 FL)', '12:19', '14:17', '16:14', '03:55', '02:10:56', '+21 30\'34"', '12.7', '3.23', '2.26', '165.56', '173.2', '-37.92'], ['21', '21 Lutetia (A852 VA)', '13:28', '14:33', '15:37', '02:08', '02:27:00', '+11 02\'05"', '10.3', '2.25', '1.28', '167.60', '174.2', '-45.61'], ['93', '93 Minerva (A867 QA)', '12:39', '14:48', '16:56', '04:16', '02:41:57', '+24 54\'22"', '12.1', '2.96', '1.98', '170.28', '171.4', '-31.79'], ['119', '119 Althaea (A872 GA)', '13:37', '14:49', '16:01', '02:24', '02:43:11', '+12 03\'00"', '11.4', '2.40', '1.41', '171.36', '174.5', '-42.62'], ['132', '132 Aethra (A873 LA)', '12:31', '15:03', '17:34', '05:03', '02:57:10', '+37 18\'21"', '12.4', '2.46', '1.51', '160.22', '158.6', '-19.36'], ['139', '139 Juewa (A874 TA)', '12:59', '15:22', '17:46', '04:46', '03:16:57', '+31 29\'40"', '12.3', '2.92', '1.95', '166.16', '161.9', '-22.14'], ['241', '241 Germania (A884 RA)', '13:18', '15:23', '17:27', '04:09', '03:17:09', '+23 36\'53"', '11.7', '2.87', '1.89', '173.90', '167.2', '-28.52'], ['409', '409 Aspasia (A895 XC)', '13:26', '15:24', '17:22', '03:56', '03:18:23', '+21 38\'41"', '11.3', '2.76', '1.77', '175.64', '167.8', '-29.92'], ['154', '154 Bertha (A875 VD)', '13:12', '15:28', '17:44', '04:31', '03:22:40', '+27 51\'17"', '12.6', '3.40', '2.42', '169.48', '163.7', '-24.38'], ['90', '90 Antiope (A866 TA)', '13:49', '15:32', '17:16', '03:27', '03:26:46', '+17 46\'50"', '12.8', '3.13', '2.14', '176.04', '166.7', '-31.67'], ['144', '144 Vibilia (A875 LA)', '14:07', '15:40', '17:12', '03:05', '03:34:11', '+15 29\'14"', '10.4', '2.13', '1.14', '173.82', '164.8', '-32.19'], ['895', '895 Helio (A918 NA)', '13:12', '15:46', '18:19', '05:06', '03:40:15', '+39 21\'55"', '12.5', '2.78', '1.84', '157.40', '152.8', '-12.99'], ['363', '363 Padua (A893 FD)', '14:13', '16:02', '17:51', '03:37', '03:56:46', '+19 03\'12"', '12.7', '2.63', '1.65', '168.86', '159.5', '-25.88'], ['481', '481 Emita (A902 CB)', '14:22', '16:03', '17:44', '03:22', '03:58:02', '+17 11\'49"', '11.7', '2.31', '1.33', '168.57', '159.3', '-26.95'], ['182', '182 Elsa (A878 CC)', '14:23', '16:04', '17:46', '03:23', '03:59:03', '+17 19\'19"', '11.1', '1.96', '0.985', '168.33', '159.0', '-26.69'], ['24', '24 Themis (A853 GA)', '14:11', '16:08', '18:04', '03:52', '04:02:21', '+21 06\'09"', '11.7', '3.08', '2.11', '167.24', '158.0', '-23.51'], ['70', '70 Panopaea (A861 JA)', '14:09', '16:17', '18:26', '04:16', '04:11:55', '+24 58\'01"', '12.2', '2.75', '1.79', '163.92', '155.1', '-19.24'], ['503', '503 Evelyn (A903 BL)', '14:26', '16:17', '18:08', '03:41', '04:11:34', '+19 31\'38"', '12.5', '2.39', '1.42', '165.34', '156.0', '-23.02'], ['65', '65 Cybele (A861 EB)', '14:44', '16:22', '18:00', '03:15', '04:16:46', '+16 30\'21"', '12.5', '3.82', '2.86', '164.04', '154.7', '-24.09'], ['113', '113 Amalthea (A871 EA)', '14:59', '16:23', '17:48', '02:48', '04:18:03', '+13 54\'51"', '12.0', '2.54', '1.57', '163.23', '154.1', '-25.53'], ['346', '346 Hermentaria (A892 WC)', '15:07', '16:34', '18:01', '02:53', '04:28:45', '+14 23\'29"', '11.0', '2.56', '1.60', '160.83', '151.6', '-23.21'], ['306', '306 Unitas (A891 EA)', '15:42', '16:35', '17:28', '01:45', '04:29:59', '+09 48\'15"', '12.2', '2.43', '1.48', '159.07', '150.3', '-25.76'], ['358', '358 Apollonia (A893 EC)', '15:04', '16:42', '18:20', '03:15', '04:36:41', '+16 32\'33"', '12.6', '2.44', '1.49', '159.30', '150.0', '-20.38'], ['95', '95 Arethusa (A867 WA)', '14:47', '16:46', '18:46', '03:59', '04:40:59', '+22 01\'54"', '11.8', '2.64', '1.69', '158.24', '149.0', '-16.17'], ['347', '347 Pariana (A892 WD)', '15:15', '16:46', '18:17', '03:02', '04:40:47', '+15 12\'43"', '13.0', '2.70', '1.75', '158.14', '148.9', '-20.40'], ['758', '758 Mancunia (A912 KB)', '15:12', '16:49', '18:27', '03:15', '04:43:59', '+16 26\'31"', '12.4', '2.72', '1.78', '157.55', '148.2', '-19.05'], ['480', '480 Hansa (A901 KB)', '15:11', '16:56', '18:41', '03:29', '04:50:51', '+18 04\'26"', '11.9', '2.54', '1.60', '156.06', '146.7', '-16.76'], ['317', '317 Roxane (A891 RD)', '15:22', '17:14', '19:06', '03:44', '05:08:44', '+19 56\'06"', '12.9', '2.26', '1.34', '151.89', '142.6', '-12.24'], ['160', '160 Una (A876 DA)', '15:09', '17:26', '19:43', '04:33', '05:20:45', '+28 17\'29"', '13.0', '2.55', '1.65', '148.27', '139.4', '-5.22'], ['498', '498 Tokio (A902 XA)', '15:57', '17:34', '19:12', '03:15', '05:29:13', '+16 30\'21"', '12.7', '2.53', '1.64', '146.79', '137.5', '-10.08'], ['389', '389 Industria (A894 EE)', '15:20', '17:39', '19:58', '04:38', '05:33:58', '+29 23\'42"', '12.2', '2.68', '1.81', '145.21', '136.4', '-2.20'], ['159', '159 Aemilia (A876 BA)', '16:19', '17:54', '19:29', '03:09', '05:49:02', '+15 55\'21"', '12.9', '2.84', '1.99', '142.00', '132.7', '-6.32'], ['704', '704 Interamnia (A910 TC)', '15:50', '18:15', '20:41*', '04:46', '06:10:24', '+32 54\'33"', '10.9', '2.78', '1.98', '136.91', '128.3', '6.29'], ['37', '37 Fides (A855 TB)', '16:00', '18:16', '20:32', '04:32', '06:10:46', '+27 59\'49"', '10.6', '2.18', '1.35', '137.40', '128.4', '4.03'], ['488', '488 Kreusa (A902 MC)', '16:15', '18:16', '20:16', '04:01', '06:10:39', '+22 23\'59"', '12.8', '3.01', '2.21', '137.51', '128.3', '1.32'], ['776', '776 Berbericia (A914 BE)', '16:26', '18:29', '20:32', '04:06', '06:23:57', '+23 11\'40"', '11.8', '2.59', '1.80', '134.48', '125.3', '4.40'], ['4', '4 Vesta (A807 FA)', '16:46', '18:35', '20:25', '03:38', '06:30:18', '+19 11\'24"', '7.25', '2.57', '1.80', '132.68', '123.4', '3.87'], ['9', '9 Metis (A848 HA)', '16:31', '18:38', '20:45*', '04:05', '06:32:36', '+24 27\'59"', '9.47', '2.09', '1.29', '132.55', '123.4', '6.74'], ['48', '48 Doris (A857 SA)', '17:22', '18:49', '20:16', '02:53', '06:44:03', '+14 22\'47"', '12.0', '2.91', '2.18', '128.66', '119.3', '4.62'], ['5', '5 Astraea (A845 XA)', '17:19', '18:54', '20:29', '03:10', '06:49:09', '+16 00\'28"', '10.7', '2.27', '1.52', '127.76', '118.4', '6.45'], ['92', '92 Undina (A867 NA)', '17:56', '19:51', '21:46*', '02:40', '07:46:24', '+20 38\'41"', '12.5', '3.33', '2.78', '115.20', '106.0', '20.73'], ['128', '128 Nemesis (A872 WA)', '18:45', '20:45*', '22:45*', '01:51', '08:40:19', '+22 04\'28"', '12.7', '2.68', '2.28', '103.23', '94.18', '33.00'], ['71', '71 Niobe (A861 PA)', '18:39', '21:02*', '23:24*', '01:57', '08:57:02', '+30 58\'26"', '12.3', '2.90', '2.54', '101.73', '93.19', '38.93'], ['78', '78 Diana (A863 EA)', '18:51', '21:03*', '23:14*', '01:45', '08:57:59', '+26 01\'25"', '12.5', '2.12', '1.71', '100.31', '91.49', '38.00'], ['451', '451 Patientia (A899 XA)', '19:46', '21:48*', '23:50*', '00:50', '09:43:24', '+22 41\'21"', '12.3', '2.93', '2.77', '89.44', '80.63', '47.11'], ['192', '192 Nausikaa (A879 DA)', '20:13', '21:58*', '23:43*', '00:23', '09:53:21', '+18 05\'01"', '12.2', '2.42', '2.28', '85.69', '76.70', '47.88'], ['31', '31 Euphrosyne (A854 RA)', '20:17', '22:48*', '01:20*', '00:19', '10:44:10', '+37 42\'15"', '11.9', '2.53', '2.45', '83.43', '76.15', '61.02']]
<class 'list'>
14
14

### dataframe 만들기

아무래도 가장 다루기 쉬운 데이타 형태인 dataframe으로 만들어 보겠습니다.

In [18]:
import pandas as pd

df = pd.DataFrame.from_dict(data['data'])
df = df.set_axis((data['fields']), axis=1)
df['OBSdate(UT)'] = obs_date
df

,Designation,Full name,Rise time,Transit time,Set time,Max. time observable,R.A.,Dec.,Vmag,Helio. range (au),Topo.range (au),Object-Observer-Sun (deg),Object-Observer-Moon (deg),Galactic latitude (deg),OBSdate(UT)
0,602,602 Marianna (A906 DJ),10:09,11:27,12:46,02:36,23:20:57,"+12 58'53""",12.6,2.31,1.59,124.75,134.0,-44.25,20231113
1,678,678 Fredegundis (A909 BQ),11:04,12:01,12:58,01:54,23:55:00,"+10 14'50""",12.4,2.02,1.22,132.21,141.5,-50.22,20231113
2,120,120 Lachesis (A872 GB),11:41,13:03,14:24,02:43,00:56:50,"+13 30'38""",13.0,3.28,2.40,147.67,157.0,-49.48,20231113
3,639,639 Latona (A907 OA),11:24,13:17,15:11,03:47,01:11:31,"+20 21'26""",12.6,2.76,1.85,151.88,160.8,-42.43,20231113
4,123,123 Brunhild (A872 OB),11:36,13:28,15:20,03:44,01:22:14,"+19 55'02""",12.5,2.42,1.49,154.40,163.3,-42.54,20231113
5,135,135 Hertha (A874 DA),12:17,13:33,14:49,02:31,01:27:15,"+12 34'47""",11.3,2.18,1.25,154.67,164.0,-49.54,20231113
6,122,122 Gerda (A872 OA),13:02,13:45,14:28,01:26,01:39:40,"+08 56'25""",12.6,3.25,2.32,156.33,165.2,-52.29,20231113
7,127,127 Johanna (A872 VB),12:42,14:10,15:39,02:56,02:04:45,"+14 38'08""",12.5,2.73,1.76,164.01,173.3,-44.83,20231113
8,509,509 Iolanda (A903 HD),12:58,14:10,15:23,02:24,02:04:33,"+12 05'15""",12.4,2.79,1.83,163.19,172.1,-47.19,20231113
9,595,595 Polyxena (A906 FL),12:19,14:17,16:14,03:55,02:10:56,"+21 30'34""",12.7,3.23,2.26,165.56,173.2,-37.92,20231113
10,21,21 Lutetia (A852 VA),13:28,14:33,15:37,02:08,02:27:00,"+11 02'05""",10.3,2.25,1.28,167.60,174.2,-45.61,20231113
11,93,93 Minerva (A867 QA),12:39,14:48,16:56,04:16,02:41:57,"+24 54'22""",12.1,2.96,1.98,170.28,171.4,-31.79,20231113
12,119,119 Althaea (A872 GA),13:37,14:49,16:01,02:24,02:43:11,"+12 03'00""",11.4,2.40,1.41,171.36,174.5,-42.62,20231113
13,132,132 Aethra (A873 LA),12:31,15:03,17:34,05:03,02:57:10,"+37 18'21""",12.4,2.46,1.51,160.22,158.6,-19.36,20231113
14,139,139 Juewa (A874 TA),12:59,15:22,17:46,04:46,03:16:57,"+31 29'40""",12.3,2.92,1.95,166.16,161.9,-22.14,20231113
15,241,241 Germania (A884 RA),13:18,15:23,17:27,04:09,03:17:09,"+23 36'53""",11.7,2.87,1.89,173.90,167.2,-28.52,20231113
16,409,409 Aspasia (A895 XC),13:26,15:24,17:22,03:56,03:18:23,"+21 38'41""",11.3,2.76,1.77,175.64,167.8,-29.92,20231113
17,154,154 Bertha (A875 VD),13:12,15:28,17:44,04:31,03:22:40,"+27 51'17""",12.6,3.40,2.42,169.48,163.7,-24.38,20231113
18,90,90 Antiope (A866 TA),13:49,15:32,17:16,03:27,03:26:46,"+17 46'50""",12.8,3.13,2.14,176.04,166.7,-31.67,20231113
19,144,144 Vibilia (A875 LA),14:07,15:40,17:12,03:05,03:34:11,"+15 29'14""",10.4,2.13,1.14,173.82,164.8,-32.19,20231113
20,895,895 Helio (A918 NA),13:12,15:46,18:19,05:06,03:40:15,"+39 21'55""",12.5,2.78,1.84,157.40,152.8,-12.99,20231113
21,363,363 Padua (A893 FD),14:13,16:02,17:51,03:37,03:56:46,"+19 03'12""",12.7,2.63,1.65,168.86,159.5,-25.88,20231113
22,481,481 Emita (A902 CB),14:22,16:03,17:44,03:22,03:58:02,"+17 11'49""",11.7,2.31,1.33,168.57,159.3,-26.95,20231113
23,182,182 Elsa (A878 CC),14:23,16:04,17:46,03:23,03:59:03,"+17 19'19""",11.1,1.96,0.985,168.33,159.0,-26.69,20231113
24,24,24 Themis (A853 GA),14:11,16:08,18:04,03:52,04:02:21,"+21 06'09""",11.7,3.08,2.11,167.24,158.0,-23.51,20231113
25,70,70 Panopaea (A861 JA),14:09,16:17,18:26,04:16,04:11:55,"+24 58'01""",12.2,2.75,1.79,163.92,155.1,-19.24,20231113
26,503,503 Evelyn (A903 BL),14:26,16:17,18:08,03:41,04:11:34,"+19 31'38""",12.5,2.39,1.42,165.34,156.0,-23.02,20231113
27,65,65 Cybele (A861 EB),14:44,16:22,18:00,03:15,04:16:46,"+16 30'21""",12.5,3.82,2.86,164.04,154.7,-24.09,20231113
28,113,113 Amalthea (A871 EA),14:59,16:23,17:48,02:48,04:18:03,"+13 54'51""",12.0,2.54,1.57,163.23,154.1,-25.53,20231113
29,346,346 Hermentaria (A892 WC),15:07,16:34,18:01,02:53,04:28:45,"+14 23'29""",11.0,2.56,1.60,160.83,151.6,-23.21,20231113
30,306,306 Unitas (A891 EA),15:42,16:35,17:28,01:45,04:29:59,"+09 48'15""",12.2,2.43,1.48,159.07,150.3,-25.76,20231113
31,358,358 Apollonia (A893 EC),15:04,16:42,18:20,03:15,04:36:41,"+16 32'33""",12.6,2.44,1.49,159.30,150.0,-20.38,20231113
32,95,95 Arethusa (A867 WA),14:47,16:46,18:46,03:59,04:40:59,"+22 01'54""",11.8,2.64,1.69,158.24,149.0,-16.17,20231113
33,347,347 Pariana (A892 WD),15:15,16:46,18:17,03:02,04:40:47,"+15 12'43""",13.0,2.70,1.75,158.14,148.9,-20.40,20231113
34,758,758 Mancunia (A912 KB),15:12,16:49,18:27,03:15,04:43:59,"+16 26'31""",12.4,2.72,1.78,157.55,148.2,-19.05,20231113
35,480,480 Hansa (A901 KB),15:11,16:56,18:41,03:29,04:50:51,"+18 04'26""",11.9,2.54,1.60,156.06,146.7,-16.76,20231113
36,317,317 Roxane (A891 RD),15:22,17:14,19:06,03:44,05:08:44,"+19 56'06""",12.9,2.26,1.34,151.89,142.6,-12.24,20231113
37,160,160 Una (A876 DA),15:09,17:26,19:43,04:33,05:20:45,"+28 17'29""",13.0,2.55,1.65,148.27,139.4,-5.22,20231113
38,498,498 Tokio (A902 XA),15:57,17:34,19:12,03:15,05:29:13,"+16 30'21""",12.7,2.53,1.64,146.79,137.5,-10.08,20231113
39,389,389 Industria (A894 EE),15:20,17:39,19:58,04:38,05:33:58,"+29 23'42""",12.2,2.68,1.81,145.21,136.4,-2.20,20231113
40,159,159 Aemilia (A876 BA),16:19,17:54,19:29,03:09,05:49:02,"+15 55'21""",12.9,2.84,1.99,142.00,132.7,-6.32,20231113
41,704,704 Interamnia (A910 TC),15:50,18:15,20:41*,04:46,06:10:24,"+32 54'33""",10.9,2.78,1.98,136.91,128.3,6.29,20231113
42,37,37 Fides (A855 TB),16:00,18:16,20:32,04:32,06:10:46,"+27 59'49""",10.6,2.18,1.35,137.40,128.4,4.03,20231113
43,488,488 Kreusa (A902 MC),16:15,18:16,20:16,04:01,06:10:39,"+22 23'59""",12.8,3.01,2.21,137.51,128.3,1.32,20231113
44,776,776 Berbericia (A914 BE),16:26,18:29,20:32,04:06,06:23:57,"+23 11'40""",11.8,2.59,1.80,134.48,125.3,4.40,20231113
45,4,4 Vesta (A807 FA),16:46,18:35,20:25,03:38,06:30:18,"+19 11'24""",7.25,2.57,1.80,132.68,123.4,3.87,20231113
46,9,9 Metis (A848 HA),16:31,18:38,20:45*,04:05,06:32:36,"+24 27'59""",9.47,2.09,1.29,132.55,123.4,6.74,20231113
47,48,48 Doris (A857 SA),17:22,18:49,20:16,02:53,06:44:03,"+14 22'47""",12.0,2.91,2.18,128.66,119.3,4.62,20231113
48,5,5 Astraea (A845 XA),17:19,18:54,20:29,03:10,06:49:09,"+16 00'28""",10.7,2.27,1.52,127.76,118.4,6.45,20231113
49,92,92 Undina (A867 NA),17:56,19:51,21:46*,02:40,07:46:24,"+20 38'41""",12.5,3.33,2.78,115.20,106.0,20.73,20231113
50,128,128 Nemesis (A872 WA),18:45,20:45*,22:45*,01:51,08:40:19,"+22 04'28""",12.7,2.68,2.28,103.23,94.18,33.00,20231113
51,71,71 Niobe (A861 PA),18:39,21:02*,23:24*,01:57,08:57:02,"+30 58'26""",12.3,2.90,2.54,101.73,93.19,38.93,20231113
52,78,78 Diana (A863 EA),18:51,21:03*,23:14*,01:45,08:57:59,"+26 01'25""",12.5,2.12,1.71,100.31,91.49,38.00,20231113
53,451,451 Patientia (A899 XA),19:46,21:48*,23:50*,00:50,09:43:24,"+22 41'21""",12.3,2.93,2.77,89.44,80.63,47.11,20231113
54,192,192 Nausikaa (A879 DA),20:13,21:58*,23:43*,00:23,09:53:21,"+18 05'01""",12.2,2.42,2.28,85.69,76.70,47.88,20231113
55,31,31 Euphrosyne (A854 RA),20:17,22:48*,01:20*,00:19,10:44:10,"+37 42'15""",11.9,2.53,2.45,83.43,76.15,61.02,20231113

### 관측 계획 저장 폴더 생성

FITS 파일을 저장할 폴더를 "OBSplan_asteroid" 이라는 이름으로 생성해보겠습니다.

* 만약 리눅스 시스템 이라면 shell 명령어로 가능한데, "!"를 붙이면 shell 명령어를 실행할 수 있습니다.
> !mkdir OBSplan_asteroid

OS의 영향을 받지 않기 위하여 pathlib을 사용하여 다음과 같이 폴더를 생성합니다.

In [19]:
import os
from pathlib import Path
BASEPATH = Path("./")
save_dir_name = "OBSplan_asteroid"
print(f"BASEPATH: {BASEPATH}")

if not (BASEPATH/save_dir_name).exists():
    os.mkdir(str(BASEPATH/save_dir_name))
    print (f"{str(BASEPATH/save_dir_name)} is created...")
else :
    print (f"{str(BASEPATH/save_dir_name)} is already exist...")

BASEPATH: .
OBSplan_asteroid is created...

### dataframe 저장

In [20]:
df.to_csv(str(BASEPATH/save_dir_name/ f'asteroid_{obs_date}.csv'))

### (과제)

12월 1달 동안의 NEA 목록을 csv  파일로 저장하는 코드를 완성하세요.

In [21]:
#(과제) 아래 코딩을 완성하여 제출하시오.
#############################################
# variables
mpc_code='P64' # Observer Location: GSHS Observatory, Suwon [code: P64]

elev_min=60 #
time_min=15
vmag_min=6
vmag_max=13
list_num=50
sort='trans'
#############################################

start_dt = datetime.strptime("2023-11-13", '%Y-%m-%d')
end_dt = datetime.strptime("2023-11-14", '%Y-%m-%d')
dt = 1

dts = [dt for dt in
            datetime_range(start_dt, end_dt,
            timedelta(days=dt))]

print("len(dts):", len(dts))
print("dts", dts)

df_all = pd.DataFrame()

for dt in dts :
    obs_datetime = dt.strftime('%Y-%m-%d %H:%M:%S')
    print("obs_datetime :", obs_datetime)
    obs_date = dt.strftime('%Y%m%d')
    print("obs_date :", obs_date)

    # Define API URL and SPK filename:
    url = 'https://ssd-api.jpl.nasa.gov/sbwobs.api'
    spk_filename = 'spk_file.bsp'

    # Get the requested SPK-ID from the command-line:
    if (len(sys.argv)) == 1:
        print("please specify SPK-ID on the command-line")
        sys.exit(2)
    spkid = sys.argv[1]

    # Build the appropriate URL for this API request:
    # IMPORTANT: You must encode the "=" as "%3D" and the ";" as "%3B" in the
    #            Horizons COMMAND parameter specification.
    url += f"?sb-kind=a&mpc-code={mpc_code}&obs-time={str(obs_datetime)}&elev-min={elev_min}&time-min={time_min}"
    url += f"&vmag-max={vmag_max}&vmag-min={vmag_min}&optical=true&fmt-ra-dec=true&mag-required=true&output-sort={sort}&maxoutput={list_num}"

    print("url :", url)

    # Submit the API request and decode the JSON-response:
    response = requests.get(url)
    try:
        data = json.loads(response.text)
        print(data)
    except ValueError:
        print("Unable to decode JSON results")

    df = pd.DataFrame.from_dict(data['data'])
    df = df.set_axis((data['fields']), axis=1)
    df['OBSdate(UT)'] = obs_date
    #print(df)

    df.to_csv(str(BASEPATH/save_dir_name/f"asteroid_{dt.strftime('%Y%m%d')}.csv"))

    df_all = pd.concat([df_all, df], axis = 0)

df_all.reset_index(inplace=True)
print("df_all :", df_all)

df_all.to_csv(str(BASEPATH/save_dir_name/f"asteroid_{dts[0].strftime('%Y%m%d')}-{dts[-1].strftime('%Y%m%d')}.csv"))

len(dts): 1
dts [datetime.datetime(2023, 11, 13, 0, 0)]
obs_datetime : 2023-11-13 00:00:00
obs_date : 20231113
url : https://ssd-api.jpl.nasa.gov/sbwobs.api?sb-kind=a&mpc-code=P64&obs-time=2023-11-13 00:00:00&elev-min=60&time-min=15&vmag-max=13&vmag-min=6&optical=true&fmt-ra-dec=true&mag-required=true&output-sort=trans&maxoutput=50

{'signature': {'source': 'NASA/JPL Small-Body Observability API', 'version': '1.0'}, 'obs_constraints': {'vmag-min': '6', 'elev-min': '60', 'vmag-max': '13', 'optical': 'true', 'mag-required': 'true', 'maxoutput': '50', 'obs-time': '2023-11-13 00:00:00', 'output-sort': 'trans', 'fmt-ra-dec': 'true', 'mpc-code': 'P64', 'time-min': '15'}, 'sb_constraints': {'sb-kind': 'a'}, 'location': 'GSHS Observatory, Suwon', 'obs_night': {'sun_set_az': '248.4', 'sun_set': '2023-11-12 08:23', 'end_civil': '2023-11-12 08:51', 'end_nautical': '2023-11-12 09:22', 'end_astronomical': '2023-11-12 09:53', 'begin_astronomical': '2023-11-12 20:36', 'begin_nautical': '2023-11-12 21:07', 'begin_civil': '2023-11-12 21:39', 'sun_rise_az': '111.8', 'sun_rise': '2023-11-12 22:06', 'transit_phase': '0.00', 'transit': '1984-10-26 23:58 ', 'moon_set_phase': '0.01', 'moon_set': '2023-11-12 07:35 ', 'moon_rise_phase': '0.00', 'moon_rise': '2023-11-12 21:46 ', 'begin_dark': '2023-11-12 09:53', 'mid_dark': '2023-11-12 15:14', 'end_dark': '2023-11-12 20:36', 'dark_time': '10:43'}, 'fields': ['Designation', 'Full name', 'Rise time', 'Transit time', 'Set time', 'Max. time observable', 'R.A.', 'Dec.', 'Vmag', 'Helio. range (au)', 'Topo.range (au)', 'Object-Observer-Sun (deg)', 'Object-Observer-Moon (deg)', 'Galactic latitude (deg)'], 'sort_by': 'transit time (asc.)', 'data': [['602', '602 Marianna (A906 DJ)', '10:09', '11:27', '12:46', '02:36', '23:20:57', '+12 58\'53"', '12.6', '2.31', '1.59', '124.75', '134.0', '-44.25'], ['678', '678 Fredegundis (A909 BQ)', '11:04', '12:01', '12:58', '01:54', '23:55:00', '+10 14\'50"', '12.4', '2.02', '1.22', '132.21', '141.5', '-50.22'], ['120', '120 Lachesis (A872 GB)', '11:41', '13:03', '14:24', '02:43', '00:56:50', '+13 30\'38"', '13.0', '3.28', '2.40', '147.67', '157.0', '-49.48'], ['639', '639 Latona (A907 OA)', '11:24', '13:17', '15:11', '03:47', '01:11:31', '+20 21\'26"', '12.6', '2.76', '1.85', '151.88', '160.8', '-42.43'], ['123', '123 Brunhild (A872 OB)', '11:36', '13:28', '15:20', '03:44', '01:22:14', '+19 55\'02"', '12.5', '2.42', '1.49', '154.40', '163.3', '-42.54'], ['135', '135 Hertha (A874 DA)', '12:17', '13:33', '14:49', '02:31', '01:27:15', '+12 34\'47"', '11.3', '2.18', '1.25', '154.67', '164.0', '-49.54'], ['122', '122 Gerda (A872 OA)', '13:02', '13:45', '14:28', '01:26', '01:39:40', '+08 56\'25"', '12.6', '3.25', '2.32', '156.33', '165.2', '-52.29'], ['127', '127 Johanna (A872 VB)', '12:42', '14:10', '15:39', '02:56', '02:04:45', '+14 38\'08"', '12.5', '2.73', '1.76', '164.01', '173.3', '-44.83'], ['509', '509 Iolanda (A903 HD)', '12:58', '14:10', '15:23', '02:24', '02:04:33', '+12 05\'15"', '12.4', '2.79', '1.83', '163.19', '172.1', '-47.19'], ['595', '595 Polyxena (A906 FL)', '12:19', '14:17', '16:14', '03:55', '02:10:56', '+21 30\'34"', '12.7', '3.23', '2.26', '165.56', '173.2', '-37.92'], ['21', '21 Lutetia (A852 VA)', '13:28', '14:33', '15:37', '02:08', '02:27:00', '+11 02\'05"', '10.3', '2.25', '1.28', '167.60', '174.2', '-45.61'], ['93', '93 Minerva (A867 QA)', '12:39', '14:48', '16:56', '04:16', '02:41:57', '+24 54\'22"', '12.1', '2.96', '1.98', '170.28', '171.4', '-31.79'], ['119', '119 Althaea (A872 GA)', '13:37', '14:49', '16:01', '02:24', '02:43:11', '+12 03\'00"', '11.4', '2.40', '1.41', '171.36', '174.5', '-42.62'], ['132', '132 Aethra (A873 LA)', '12:31', '15:03', '17:34', '05:03', '02:57:10', '+37 18\'21"', '12.4', '2.46', '1.51', '160.22', '158.6', '-19.36'], ['139', '139 Juewa (A874 TA)', '12:59', '15:22', '17:46', '04:46', '03:16:57', '+31 29\'40"', '12.3', '2.92', '1.95', '166.16', '161.9', '-22.14'], ['241', '241 Germania (A884 RA)', '13:18', '15:23', '17:27', '04:09', '03:17:09', '+23 36\'53"', '11.7', '2.87', '1.89', '173.90', '167.2', '-28.52'], ['409', '409 Aspasia (A895 XC)', '13:26', '15:24', '17:22', '03:56', '03:18:23', '+21 38\'41"', '11.3', '2.76', '1.77', '175.64', '167.8', '-29.92'], ['154', '154 Bertha (A875 VD)', '13:12', '15:28', '17:44', '04:31', '03:22:40', '+27 51\'17"', '12.6', '3.40', '2.42', '169.48', '163.7', '-24.38'], ['90', '90 Antiope (A866 TA)', '13:49', '15:32', '17:16', '03:27', '03:26:46', '+17 46\'50"', '12.8', '3.13', '2.14', '176.04', '166.7', '-31.67'], ['144', '144 Vibilia (A875 LA)', '14:07', '15:40', '17:12', '03:05', '03:34:11', '+15 29\'14"', '10.4', '2.13', '1.14', '173.82', '164.8', '-32.19'], ['895', '895 Helio (A918 NA)', '13:12', '15:46', '18:19', '05:06', '03:40:15', '+39 21\'55"', '12.5', '2.78', '1.84', '157.40', '152.8', '-12.99'], ['363', '363 Padua (A893 FD)', '14:13', '16:02', '17:51', '03:37', '03:56:46', '+19 03\'12"', '12.7', '2.63', '1.65', '168.86', '159.5', '-25.88'], ['481', '481 Emita (A902 CB)', '14:22', '16:03', '17:44', '03:22', '03:58:02', '+17 11\'49"', '11.7', '2.31', '1.33', '168.57', '159.3', '-26.95'], ['182', '182 Elsa (A878 CC)', '14:23', '16:04', '17:46', '03:23', '03:59:03', '+17 19\'19"', '11.1', '1.96', '0.985', '168.33', '159.0', '-26.69'], ['24', '24 Themis (A853 GA)', '14:11', '16:08', '18:04', '03:52', '04:02:21', '+21 06\'09"', '11.7', '3.08', '2.11', '167.24', '158.0', '-23.51'], ['70', '70 Panopaea (A861 JA)', '14:09', '16:17', '18:26', '04:16', '04:11:55', '+24 58\'01"', '12.2', '2.75', '1.79', '163.92', '155.1', '-19.24'], ['503', '503 Evelyn (A903 BL)', '14:26', '16:17', '18:08', '03:41', '04:11:34', '+19 31\'38"', '12.5', '2.39', '1.42', '165.34', '156.0', '-23.02'], ['65', '65 Cybele (A861 EB)', '14:44', '16:22', '18:00', '03:15', '04:16:46', '+16 30\'21"', '12.5', '3.82', '2.86', '164.04', '154.7', '-24.09'], ['113', '113 Amalthea (A871 EA)', '14:59', '16:23', '17:48', '02:48', '04:18:03', '+13 54\'51"', '12.0', '2.54', '1.57', '163.23', '154.1', '-25.53'], ['346', '346 Hermentaria (A892 WC)', '15:07', '16:34', '18:01', '02:53', '04:28:45', '+14 23\'29"', '11.0', '2.56', '1.60', '160.83', '151.6', '-23.21'], ['306', '306 Unitas (A891 EA)', '15:42', '16:35', '17:28', '01:45', '04:29:59', '+09 48\'15"', '12.2', '2.43', '1.48', '159.07', '150.3', '-25.76'], ['358', '358 Apollonia (A893 EC)', '15:04', '16:42', '18:20', '03:15', '04:36:41', '+16 32\'33"', '12.6', '2.44', '1.49', '159.30', '150.0', '-20.38'], ['95', '95 Arethusa (A867 WA)', '14:47', '16:46', '18:46', '03:59', '04:40:59', '+22 01\'54"', '11.8', '2.64', '1.69', '158.24', '149.0', '-16.17'], ['347', '347 Pariana (A892 WD)', '15:15', '16:46', '18:17', '03:02', '04:40:47', '+15 12\'43"', '13.0', '2.70', '1.75', '158.14', '148.9', '-20.40'], ['758', '758 Mancunia (A912 KB)', '15:12', '16:49', '18:27', '03:15', '04:43:59', '+16 26\'31"', '12.4', '2.72', '1.78', '157.55', '148.2', '-19.05'], ['480', '480 Hansa (A901 KB)', '15:11', '16:56', '18:41', '03:29', '04:50:51', '+18 04\'26"', '11.9', '2.54', '1.60', '156.06', '146.7', '-16.76'], ['317', '317 Roxane (A891 RD)', '15:22', '17:14', '19:06', '03:44', '05:08:44', '+19 56\'06"', '12.9', '2.26', '1.34', '151.89', '142.6', '-12.24'], ['160', '160 Una (A876 DA)', '15:09', '17:26', '19:43', '04:33', '05:20:45', '+28 17\'29"', '13.0', '2.55', '1.65', '148.27', '139.4', '-5.22'], ['498', '498 Tokio (A902 XA)', '15:57', '17:34', '19:12', '03:15', '05:29:13', '+16 30\'21"', '12.7', '2.53', '1.64', '146.79', '137.5', '-10.08'], ['389', '389 Industria (A894 EE)', '15:20', '17:39', '19:58', '04:38', '05:33:58', '+29 23\'42"', '12.2', '2.68', '1.81', '145.21', '136.4', '-2.20'], ['159', '159 Aemilia (A876 BA)', '16:19', '17:54', '19:29', '03:09', '05:49:02', '+15 55\'21"', '12.9', '2.84', '1.99', '142.00', '132.7', '-6.32'], ['704', '704 Interamnia (A910 TC)', '15:50', '18:15', '20:41*', '04:46', '06:10:24', '+32 54\'33"', '10.9', '2.78', '1.98', '136.91', '128.3', '6.29'], ['37', '37 Fides (A855 TB)', '16:00', '18:16', '20:32', '04:32', '06:10:46', '+27 59\'49"', '10.6', '2.18', '1.35', '137.40', '128.4', '4.03'], ['488', '488 Kreusa (A902 MC)', '16:15', '18:16', '20:16', '04:01', '06:10:39', '+22 23\'59"', '12.8', '3.01', '2.21', '137.51', '128.3', '1.32'], ['776', '776 Berbericia (A914 BE)', '16:26', '18:29', '20:32', '04:06', '06:23:57', '+23 11\'40"', '11.8', '2.59', '1.80', '134.48', '125.3', '4.40'], ['4', '4 Vesta (A807 FA)', '16:46', '18:35', '20:25', '03:38', '06:30:18', '+19 11\'24"', '7.25', '2.57', '1.80', '132.68', '123.4', '3.87'], ['9', '9 Metis (A848 HA)', '16:31', '18:38', '20:45*', '04:05', '06:32:36', '+24 27\'59"', '9.47', '2.09', '1.29', '132.55', '123.4', '6.74'], ['48', '48 Doris (A857 SA)', '17:22', '18:49', '20:16', '02:53', '06:44:03', '+14 22\'47"', '12.0', '2.91', '2.18', '128.66', '119.3', '4.62'], ['5', '5 Astraea (A845 XA)', '17:19', '18:54', '20:29', '03:10', '06:49:09', '+16 00\'28"', '10.7', '2.27', '1.52', '127.76', '118.4', '6.45'], ['92', '92 Undina (A867 NA)', '17:56', '19:51', '21:46*', '02:40', '07:46:24', '+20 38\'41"', '12.5', '3.33', '2.78', '115.20', '106.0', '20.73']], 'total_objects': '56', 'shown_objects': '50'}
df_all :     index Designation                  Full name Rise time Transit time  \
0       0         602     602 Marianna (A906 DJ)     10:09        11:27
1       1         678  678 Fredegundis (A909 BQ)     11:04        12:01
2       2         120     120 Lachesis (A872 GB)     11:41        13:03
3       3         639       639 Latona (A907 OA)     11:24        13:17
4       4         123     123 Brunhild (A872 OB)     11:36        13:28
5       5         135       135 Hertha (A874 DA)     12:17        13:33
6       6         122        122 Gerda (A872 OA)     13:02        13:45
7       7         127      127 Johanna (A872 VB)     12:42        14:10
8       8         509      509 Iolanda (A903 HD)     12:58        14:10
9       9         595     595 Polyxena (A906 FL)     12:19        14:17
10     10          21       21 Lutetia (A852 VA)     13:28        14:33
11     11          93       93 Minerva (A867 QA)     12:39        14:48
12     12         119      119 Althaea (A872 GA)     13:37        14:49
13     13         132       132 Aethra (A873 LA)     12:31        15:03
14     14         139        139 Juewa (A874 TA)     12:59        15:22
15     15         241     241 Germania (A884 RA)     13:18        15:23
16     16         409      409 Aspasia (A895 XC)     13:26        15:24
17     17         154       154 Bertha (A875 VD)     13:12        15:28
18     18          90       90 Antiope (A866 TA)     13:49        15:32
19     19         144      144 Vibilia (A875 LA)     14:07        15:40
20     20         895        895 Helio (A918 NA)     13:12        15:46
21     21         363        363 Padua (A893 FD)     14:13        16:02
22     22         481        481 Emita (A902 CB)     14:22        16:03
23     23         182         182 Elsa (A878 CC)     14:23        16:04
24     24          24        24 Themis (A853 GA)     14:11        16:08
25     25          70      70 Panopaea (A861 JA)     14:09        16:17
26     26         503       503 Evelyn (A903 BL)     14:26        16:17
27     27          65        65 Cybele (A861 EB)     14:44        16:22
28     28         113     113 Amalthea (A871 EA)     14:59        16:23
29     29         346  346 Hermentaria (A892 WC)     15:07        16:34
30     30         306       306 Unitas (A891 EA)     15:42        16:35
31     31         358    358 Apollonia (A893 EC)     15:04        16:42
32     32          95      95 Arethusa (A867 WA)     14:47        16:46
33     33         347      347 Pariana (A892 WD)     15:15        16:46
34     34         758     758 Mancunia (A912 KB)     15:12        16:49
35     35         480        480 Hansa (A901 KB)     15:11        16:56
36     36         317       317 Roxane (A891 RD)     15:22        17:14
37     37         160          160 Una (A876 DA)     15:09        17:26
38     38         498        498 Tokio (A902 XA)     15:57        17:34
39     39         389    389 Industria (A894 EE)     15:20        17:39
40     40         159      159 Aemilia (A876 BA)     16:19        17:54
41     41         704   704 Interamnia (A910 TC)     15:50        18:15
42     42          37         37 Fides (A855 TB)     16:00        18:16
43     43         488       488 Kreusa (A902 MC)     16:15        18:16
44     44         776   776 Berbericia (A914 BE)     16:26        18:29
45     45           4          4 Vesta (A807 FA)     16:46        18:35
46     46           9          9 Metis (A848 HA)     16:31        18:38
47     47          48         48 Doris (A857 SA)     17:22        18:49
48     48           5        5 Astraea (A845 XA)     17:19        18:54
49     49          92        92 Undina (A867 NA)     17:56        19:51

   Set time Max. time observable      R.A.        Dec.  Vmag  \
0     12:46                02:36  23:20:57  +12 58'53"  12.6
1     12:58                01:54  23:55:00  +10 14'50"  12.4
2     14:24                02:43  00:56:50  +13 30'38"  13.0
3     15:11                03:47  01:11:31  +20 21'26"  12.6
4     15:20                03:44  01:22:14  +19 55'02"  12.5
5     14:49                02:31  01:27:15  +12 34'47"  11.3
6     14:28                01:26  01:39:40  +08 56'25"  12.6
7     15:39                02:56  02:04:45  +14 38'08"  12.5
8     15:23                02:24  02:04:33  +12 05'15"  12.4
9     16:14                03:55  02:10:56  +21 30'34"  12.7
10    15:37                02:08  02:27:00  +11 02'05"  10.3
11    16:56                04:16  02:41:57  +24 54'22"  12.1
12    16:01                02:24  02:43:11  +12 03'00"  11.4
13    17:34                05:03  02:57:10  +37 18'21"  12.4
14    17:46                04:46  03:16:57  +31 29'40"  12.3
15    17:27                04:09  03:17:09  +23 36'53"  11.7
16    17:22                03:56  03:18:23  +21 38'41"  11.3
17    17:44                04:31  03:22:40  +27 51'17"  12.6
18    17:16                03:27  03:26:46  +17 46'50"  12.8
19    17:12                03:05  03:34:11  +15 29'14"  10.4
20    18:19                05:06  03:40:15  +39 21'55"  12.5
21    17:51                03:37  03:56:46  +19 03'12"  12.7
22    17:44                03:22  03:58:02  +17 11'49"  11.7
23    17:46                03:23  03:59:03  +17 19'19"  11.1
24    18:04                03:52  04:02:21  +21 06'09"  11.7
25    18:26                04:16  04:11:55  +24 58'01"  12.2
26    18:08                03:41  04:11:34  +19 31'38"  12.5
27    18:00                03:15  04:16:46  +16 30'21"  12.5
28    17:48                02:48  04:18:03  +13 54'51"  12.0
29    18:01                02:53  04:28:45  +14 23'29"  11.0
30    17:28                01:45  04:29:59  +09 48'15"  12.2
31    18:20                03:15  04:36:41  +16 32'33"  12.6
32    18:46                03:59  04:40:59  +22 01'54"  11.8
33    18:17                03:02  04:40:47  +15 12'43"  13.0
34    18:27                03:15  04:43:59  +16 26'31"  12.4
35    18:41                03:29  04:50:51  +18 04'26"  11.9
36    19:06                03:44  05:08:44  +19 56'06"  12.9
37    19:43                04:33  05:20:45  +28 17'29"  13.0
38    19:12                03:15  05:29:13  +16 30'21"  12.7
39    19:58                04:38  05:33:58  +29 23'42"  12.2
40    19:29                03:09  05:49:02  +15 55'21"  12.9
41   20:41*                04:46  06:10:24  +32 54'33"  10.9
42    20:32                04:32  06:10:46  +27 59'49"  10.6
43    20:16                04:01  06:10:39  +22 23'59"  12.8
44    20:32                04:06  06:23:57  +23 11'40"  11.8
45    20:25                03:38  06:30:18  +19 11'24"  7.25
46   20:45*                04:05  06:32:36  +24 27'59"  9.47
47    20:16                02:53  06:44:03  +14 22'47"  12.0
48    20:29                03:10  06:49:09  +16 00'28"  10.7
49   21:46*                02:40  07:46:24  +20 38'41"  12.5

   Helio. range (au) Topo.range (au) Object-Observer-Sun (deg)  \
0               2.31            1.59                    124.75
1               2.02            1.22                    132.21
2               3.28            2.40                    147.67
3               2.76            1.85                    151.88
4               2.42            1.49                    154.40
5               2.18            1.25                    154.67
6               3.25            2.32                    156.33
7               2.73            1.76                    164.01
8               2.79            1.83                    163.19
9               3.23            2.26                    165.56
10              2.25            1.28                    167.60
11              2.96            1.98                    170.28
12              2.40            1.41                    171.36
13              2.46            1.51                    160.22
14              2.92            1.95                    166.16
15              2.87            1.89                    173.90
16              2.76            1.77                    175.64
17              3.40            2.42                    169.48
18              3.13            2.14                    176.04
19              2.13            1.14                    173.82
20              2.78            1.84                    157.40
21              2.63            1.65                    168.86
22              2.31            1.33                    168.57
23              1.96           0.985                    168.33
24              3.08            2.11                    167.24
25              2.75            1.79                    163.92
26              2.39            1.42                    165.34
27              3.82            2.86                    164.04
28              2.54            1.57                    163.23
29              2.56            1.60                    160.83
30              2.43            1.48                    159.07
31              2.44            1.49                    159.30
32              2.64            1.69                    158.24
33              2.70            1.75                    158.14
34              2.72            1.78                    157.55
35              2.54            1.60                    156.06
36              2.26            1.34                    151.89
37              2.55            1.65                    148.27
38              2.53            1.64                    146.79
39              2.68            1.81                    145.21
40              2.84            1.99                    142.00
41              2.78            1.98                    136.91
42              2.18            1.35                    137.40
43              3.01            2.21                    137.51
44              2.59            1.80                    134.48
45              2.57            1.80                    132.68
46              2.09            1.29                    132.55
47              2.91            2.18                    128.66
48              2.27            1.52                    127.76
49              3.33            2.78                    115.20

   Object-Observer-Moon (deg) Galactic latitude (deg) OBSdate(UT)
0                       134.0                  -44.25    20231113
1                       141.5                  -50.22    20231113
2                       157.0                  -49.48    20231113
3                       160.8                  -42.43    20231113
4                       163.3                  -42.54    20231113
5                       164.0                  -49.54    20231113
6                       165.2                  -52.29    20231113
7                       173.3                  -44.83    20231113
8                       172.1                  -47.19    20231113
9                       173.2                  -37.92    20231113
10                      174.2                  -45.61    20231113
11                      171.4                  -31.79    20231113
12                      174.5                  -42.62    20231113
13                      158.6                  -19.36    20231113
14                      161.9                  -22.14    20231113
15                      167.2                  -28.52    20231113

## 소행성 좌표 얻기

### 소행성 id 잘라내기

앞서 얻은 dataframe로 부터 소행성의 이름을 알아보자.

In [22]:
#print("df :", df)
#print("df['Full name'] :", df['Full name'])
print("df['Full name'][0] :", df['Full name'][0])

#import re
#asteroid_names = re.findall('\(([^)]+)', df['Full name'][0])   #extracts string in bracket()
#print (asteroid_names[0])

asteroid_id = df['Full name'][0].split(" ")[0]   #extracts string in bracket()
print("asteroid_id :", asteroid_id)
obs_date = df['OBSdate(UT)'][0]

df['Full name'][0] : 602 Marianna (A906 DJ)
asteroid_id : 602

### astroquery.mpc

[astroquery.mpc](https://astroquery.readthedocs.io/en/latest/mpc/mpc.html) 를 이용하여 시간에 따른 소행성의 좌표를 얻어보자.

In [23]:
from astroquery.mpc import MPC
eph = MPC.get_ephemeris(asteroid_id, step='1h', number=30 * 24)
print("type(eph) :", type(eph))
print("eph :", eph)
df_eph = eph.to_pandas()
df_eph

type(eph) : <class 'astropy.table.table.Table'>
eph :           Date                  RA         ... Uncertainty 3sig Unc. P.A.
                               deg         ...      arcsec         deg
----------------------- ------------------ ... ---------------- ---------
2023-11-13 11:00:00.000  349.9858333333333 ...                0      48.9
2023-11-13 12:00:00.000  349.9879166666666 ...                0      48.9
2023-11-13 13:00:00.000 349.99041666666665 ...                0      48.9
2023-11-13 14:00:00.000 349.99291666666664 ...                0      48.9
2023-11-13 15:00:00.000  349.9954166666666 ...                0      48.9
2023-11-13 16:00:00.000 349.99791666666664 ...                0      48.9
2023-11-13 17:00:00.000  350.0004166666666 ...                0      48.9
2023-11-13 18:00:00.000 350.00291666666664 ...                0      48.9
2023-11-13 19:00:00.000 350.00541666666663 ...                0      48.9
2023-11-13 20:00:00.000  350.0079166666666 ...                0      48.9
                    ...                ... ...              ...       ...
2023-12-13 01:00:00.000 354.66416666666663 ...                0      49.8
2023-12-13 02:00:00.000  354.6741666666666 ...                0      49.8
2023-12-13 03:00:00.000  354.6845833333333 ...                0      49.8
2023-12-13 04:00:00.000            354.695 ...                0      49.8
2023-12-13 05:00:00.000  354.7049999999999 ...                0      49.8
2023-12-13 06:00:00.000  354.7154166666666 ...                0      49.8
2023-12-13 07:00:00.000  354.7254166666666 ...                0      49.8
2023-12-13 08:00:00.000  354.7358333333333 ...                0      49.8
2023-12-13 09:00:00.000          354.74625 ...                0      49.8
2023-12-13 10:00:00.000  354.7562499999999 ...                0      49.8
Length = 720 rows

,Date,RA,Dec,Delta,r,Elongation,Phase,V,Proper motion,Direction,Uncertainty 3sig,Unc. P.A.
0,2023-11-13 11:00:00,349.985833,12.858333,1.603,2.307,124.0,20.8,12.6,8.69,79.3,0,48.9
1,2023-11-13 12:00:00,349.987917,12.858889,1.603,2.307,124.0,20.8,12.6,8.74,79.3,0,48.9
2,2023-11-13 13:00:00,349.990417,12.859167,1.603,2.307,123.9,20.9,12.6,8.78,79.3,0,48.9
3,2023-11-13 14:00:00,349.992917,12.859722,1.604,2.307,123.9,20.9,12.6,8.83,79.3,0,48.9
4,2023-11-13 15:00:00,349.995417,12.860278,1.604,2.307,123.9,20.9,12.6,8.88,79.3,0,48.9
...,...,...,...,...,...,...,...,...,...,...,...,...
715,2023-12-13 06:00:00,354.715417,14.033611,1.932,2.314,99.9,24.8,13.1,37.27,73.9,0,49.8
716,2023-12-13 07:00:00,354.725417,14.036389,1.932,2.314,99.9,24.8,13.1,37.31,73.9,0,49.8
717,2023-12-13 08:00:00,354.735833,14.039444,1.933,2.314,99.8,24.8,13.1,37.34,73.9,0,49.8
718,2023-12-13 09:00:00,354.746250,14.042222,1.933,2.314,99.8,24.8,13.1,37.37,73.9,0,49.8
719,2023-12-13 10:00:00,354.756250,14.045278,1.934,2.314,99.8,24.8,13.1,37.40,73.9,0,49.8

### 최대 움직임 속도 알아보기

In [24]:
print(f"Proper motion: {eph['Proper motion'].quantity.to('arcmin/h').max():.03f}")

Proper motion: 0.623 arcmin / h

### 파일 저장하기

In [25]:
eph = MPC.get_ephemeris(asteroid_id, location='P64',
                        ra_format={'sep': ':', 'unit': 'hourangle', 'precision': 1},
                        dec_format={'sep': ':', 'precision': 0},
                        step='1h')
print("type(eph): ", type(eph))
#print("eph: ", eph)
df_eph = eph.to_pandas()
df_eph['Asteroid ID'] = asteroid_id
df_eph['Asteroid name'] = df['Full name'][0]
df_eph.to_csv(str(BASEPATH/save_dir_name/ f'asteroid_{asteroid_id}.csv'))
df_eph

type(eph):  <class 'astropy.table.table.Table'>

,Date,RA,Dec,Delta,r,Elongation,Phase,V,Proper motion,Direction,Azimuth,Altitude,Sun altitude,Moon phase,Moon distance,Moon altitude,Uncertainty 3sig,Unc. P.A.,Asteroid ID,Asteroid name
0,2023-11-13 11:00:00,23:19:56.6,12:51:28,1.602,2.307,124.0,20.8,12.6,7.58,77.5,167,65,-31,0.00,124,-33,0,48.9,602,602 Marianna (A906 DJ)
1,2023-11-13 12:00:00,23:19:57.1,12:51:29,1.603,2.307,124.0,20.8,12.6,7.62,78.0,201,64,-43,0.00,124,-45,0,48.9,602,602 Marianna (A906 DJ)
2,2023-11-13 13:00:00,23:19:57.6,12:51:31,1.603,2.307,123.9,20.9,12.6,7.74,78.6,228,57,-55,0.00,123,-56,0,48.9,602,602 Marianna (A906 DJ)
3,2023-11-13 14:00:00,23:19:58.1,12:51:33,1.604,2.307,123.9,20.9,12.6,7.93,79.2,246,47,-65,0.00,122,-66,0,48.9,602,602 Marianna (A906 DJ)
4,2023-11-13 15:00:00,23:19:58.7,12:51:34,1.604,2.307,123.9,20.9,12.6,8.18,79.8,258,36,-71,0.00,122,-73,0,48.9,602,602 Marianna (A906 DJ)
5,2023-11-13 16:00:00,23:19:59.2,12:51:35,1.605,2.307,123.8,20.9,12.6,8.48,80.3,268,24,-68,0.00,121,-72,0,48.9,602,602 Marianna (A906 DJ)
6,2023-11-13 17:00:00,23:19:59.8,12:51:37,1.605,2.307,123.8,20.9,12.6,8.82,80.7,277,12,-60,0.00,121,-64,0,48.9,602,602 Marianna (A906 DJ)
7,2023-11-13 18:00:00,23:20:00.4,12:51:38,1.605,2.307,123.7,20.9,12.6,9.16,81.0,286,0,-49,0.00,120,-54,0,48.9,602,602 Marianna (A906 DJ)
8,2023-11-13 19:00:00,23:20:01.1,12:51:40,1.606,2.307,123.7,20.9,12.6,9.49,81.1,296,-11,-37,0.00,120,-42,0,48.9,602,602 Marianna (A906 DJ)
9,2023-11-13 20:00:00,23:20:01.7,12:51:41,1.606,2.307,123.7,20.9,12.6,9.80,81.1,306,-21,-25,0.00,119,-31,0,48.9,602,602 Marianna (A906 DJ)
10,2023-11-13 21:00:00,23:20:02.4,12:51:43,1.607,2.307,123.6,20.9,12.6,10.05,81.0,319,-30,-14,0.00,119,-20,0,49.0,602,602 Marianna (A906 DJ)
11,2023-11-13 22:00:00,23:20:03.1,12:51:44,1.607,2.307,123.6,20.9,12.6,10.25,80.8,335,-37,-2,0.00,118,-9,0,48.9,602,602 Marianna (A906 DJ)
12,2023-11-13 23:00:00,23:20:03.8,12:51:46,1.607,2.307,123.6,20.9,12.6,10.37,80.5,353,-40,9,0.00,118,2,0,48.9,602,602 Marianna (A906 DJ)
13,2023-11-14 00:00:00,23:20:04.5,12:51:48,1.608,2.307,123.5,21.0,12.6,10.42,80.1,12,-39,18,0.00,117,11,0,48.9,602,602 Marianna (A906 DJ)
14,2023-11-14 01:00:00,23:20:05.2,12:51:50,1.608,2.307,123.5,21.0,12.6,10.39,79.6,30,-35,26,0.00,117,19,0,48.9,602,602 Marianna (A906 DJ)
15,2023-11-14 02:00:00,23:20:05.9,12:51:52,1.609,2.307,123.5,21.0,12.6,10.29,79.1,45,-28,32,0.01,116,25,0,48.9,602,602 Marianna (A906 DJ)
16,2023-11-14 03:00:00,23:20:06.5,12:51:53,1.609,2.307,123.4,21.0,12.6,10.13,78.6,57,-18,35,0.01,116,29,0,48.9,602,602 Marianna (A906 DJ)
17,2023-11-14 04:00:00,23:20:07.2,12:51:56,1.609,2.307,123.4,21.0,12.6,9.93,78.2,68,-8,34,0.01,115,29,0,48.9,602,602 Marianna (A906 DJ)
18,2023-11-14 05:00:00,23:20:07.9,12:51:58,1.610,2.307,123.3,21.0,12.6,9.69,77.7,77,4,30,0.01,115,27,0,48.9,602,602 Marianna (A906 DJ)
19,2023-11-14 06:00:00,23:20:08.5,12:52:00,1.610,2.307,123.3,21.0,12.6,9.45,77.3,86,16,22,0.01,114,22,0,48.9,602,602 Marianna (A906 DJ)
20,2023-11-14 07:00:00,23:20:09.1,12:52:02,1.611,2.307,123.3,21.0,12.6,9.21,77.1,95,28,14,0.01,114,15,0,48.9,602,602 Marianna (A906 DJ)
21,2023-11-14 08:00:00,23:20:09.7,12:52:04,1.611,2.307,123.2,21.0,12.6,9.01,76.9,105,39,3,0.01,113,6,0,48.9,602,602 Marianna (A906 DJ)
22,2023-11-14 09:00:00,23:20:10.3,12:52:06,1.611,2.307,123.2,21.0,12.6,8.85,76.9,119,51,-8,0.01,113,-3,0,48.9,602,602 Marianna (A906 DJ)
23,2023-11-14 10:00:00,23:20:10.9,12:52:08,1.612,2.307,123.2,21.0,12.6,8.75,77.1,139,60,-20,0.01,112,-14,0,48.9,602,602 Marianna (A906 DJ)
24,2023-11-14 11:00:00,23:20:11.5,12:52:10,1.612,2.307,123.1,21.1,12.6,8.72,77.4,169,65,-32,0.01,112,-25,0,48.9,602,602 Marianna (A906 DJ)
25,2023-11-14 12:00:00,23:20:12.1,12:52:12,1.613,2.307,123.1,21.1,12.6,8.76,77.9,203,64,-43,0.01,111,-37,0,48.9,602,602 Marianna (A906 DJ)
26,2023-11-14 13:00:00,23:20:12.7,12:52:13,1.613,2.307,123.0,21.1,12.6,8.88,78.4,230,57,-55,0.02,111,-48,0,48.9,602,602 Marianna (A906 DJ)
27,2023-11-14 14:00:00,23:20:13.3,12:52:15,1.614,2.307,123.0,21.1,12.6,9.08,78.9,247,47,-65,0.02,110,-59,0,48.9,602,602 Marianna (A906 DJ)
28,2023-11-14 15:00:00,23:20:13.9,12:52:17,1.614,2.307,123.0,21.1,12.6,9.33,79.4,259,35,-71,0.02,110,-70,0,48.9,602,602 Marianna (A906 DJ)
29,2023-11-14 16:00:00,23:20:14.5,12:52:19,1.614,2.307,122.9,21.1,12.6,9.63,79.9,269,23,-69,0.02,109,-77,0,48.9,602,602 Marianna (A906 DJ)
30,2023-11-14 17:00:00,23:20:15.2,12:52:20,1.615,2.307,122.9,21.1,12.6,9.97,80.3,278,11,-60,0.02,109,-75,0,48.9,602,602 Marianna (A906 DJ)
31,2023-11-14 18:00:00,23:20:15.9,12:52:22,1.615,2.307,122.9,21.1,12.6,10.31,80.5,287,0,-49,0.02,108,-65,0,48.9,602,602 Marianna (A906 DJ)
32,2023-11-14 19:00:00,23:20:16.6,12:52:24,1.616,2.307,122.8,21.1,12.6,10.64,80.6,296,-12,-38,0.02,108,-54,0,48.9,602,602 Marianna (A906 DJ)
33,2023-11-14 20:00:00,23:20:17.3,12:52:25,1.616,2.307,122.8,21.1,12.6,10.94,80.6,307,-22,-26,0.02,107,-43,0,48.9,602,602 Marianna (A906 DJ)
34,2023-11-14 21:00:00,23:20:18.1,12:52:27,1.616,2.307,122.7,21.1,12.6,11.19,80.5,320,-30,-14,0.03,106,-32,0,48.9,602,602 Marianna (A906 DJ)
35,2023-11-14 22:00:00,23:20:18.8,12:52:29,1.617,2.307,122.7,21.2,12.6,11.38,80.3,336,-37,-2,0.03,106,-21,0,48.9,602,602 Marianna (A906 DJ)
36,2023-11-14 23:00:00,23:20:19.6,12:52:31,1.617,2.307,122.7,21.2,12.6,11.50,80.0,355,-40,8,0.03,105,-10,0,48.9,602,602 Marianna (A906 DJ)
37,2023-11-15 00:00:00,23:20:20.4,12:52:33,1.618,2.307,122.6,21.2,12.6,11.54,79.7,14,-39,18,0.03,105,0,0,48.9,602,602 Marianna (A906 DJ)
38,2023-11-15 01:00:00,23:20:21.1,12:52:35,1.618,2.307,122.6,21.2,12.6,11.51,79.3,31,-34,26,0.03,104,9,0,48.9,602,602 Marianna (A906 DJ)
39,2023-11-15 02:00:00,23:20:21.9,12:52:37,1.619,2.307,122.6,21.2,12.6,11.41,78.8,46,-27,32,0.03,104,17,0,48.9,602,602 Marianna (A906 DJ)
40,2023-11-15 03:00:00,23:20:22.7,12:52:40,1.619,2.307,122.5,21.2,12.6,11.24,78.4,58,-18,34,0.03,103,22,0,48.9,602,602 Marianna (A906 DJ)
41,2023-11-15 04:00:00,23:20:23.4,12:52:42,1.619,2.307,122.5,21.2,12.6,11.04,77.9,68,-7,34,0.04,103,26,0,48.9,602,602 Marianna (A906 DJ)
42,2023-11-15 05:00:00,23:20:24.1,12:52:44,1.620,2.307,122.5,21.2,12.6,10.80,77.5,77,5,29,0.04,102,26,0,48.9,602,602 Marianna (A906 DJ)
43,2023-11-15 06:00:00,23:20:24.9,12:52:47,1.620,2.307,122.4,21.2,12.6,10.56,77.2,86,16,22,0.04,102,24,0,48.9,602,602 Marianna (A906 DJ)
44,2023-11-15 07:00:00,23:20:25.6,12:52:49,1.621,2.307,122.4,21.2,12.6,10.33,77.0,95,28,13,0.04,101,19,0,48.9,602,602 Marianna (A906 DJ)
45,2023-11-15 08:00:00,23:20:26.2,12:52:51,1.621,2.307,122.3,21.2,12.6,10.12,76.8,106,40,3,0.04,101,12,0,48.9,602,602 Marianna (A906 DJ)
46,2023-11-15 09:00:00,23:20:26.9,12:52:53,1.621,2.307,122.3,21.2,12.6,9.97,76.9,120,51,-8,0.05,100,4,0,48.9,602,602 Marianna (A906 DJ)
47,2023-11-15 10:00:00,23:20:27.6,12:52:56,1.622,2.307,122.3,21.3,12.6,9.87,77.0,140,60,-20,0.05,100,-6,0,48.9,602,602 Marianna (A906 DJ)
48,2023-11-15 11:00:00,23:20:28.2,12:52:58,1.622,2.307,122.2,21.3,12.6,9.85,77.3,171,66,-32,0.05,99,-16,0,48.9,602,602 Marianna (A906 DJ)

### (과제)

df에 있는 소행성 목록들의 eph를 csv 파일로 저장해 보자.

In [26]:
from pathlib import Path
from astroquery.mpc import MPC
from pprint import pprint
import re

for i, row  in df.iterrows():
    print("row['Full name'] :", row["Full name"])

    #asteroid_names = re.findall('\(([^)]+)', df['Full name'][0])   #extracts string in bracket()
    #print (asteroid_names[0])
    asteroid_id = df['Full name'][i].split(" ")[0]   #extracts string
    print(asteroid_id)

    eph = MPC.get_ephemeris(asteroid_id, step='1h', number=30 * 24)
    print(f"Proper motion: {eph['Proper motion'].quantity.to('arcmin/h').max():.03f}")
    eph = MPC.get_ephemeris(asteroid_id, location='P64',
                        ra_format={'sep': ':', 'unit': 'hourangle', 'precision': 1},
                        dec_format={'sep': ':', 'precision': 0},
                        step='1h')
    print("type(eph): ", type(eph))
    #print("eph: ", eph)

    df_eph = eph.to_pandas()
    df_eph['Asteroid ID'] = asteroid_id
    df_eph['Asteroid name'] = df['Full name'][i]
    df_eph.to_csv(str(BASEPATH/save_dir_name/ f"eph_asteroid_{asteroid_id}.csv"))

row['Full name'] : 602 Marianna (A906 DJ)
602
Proper motion: 0.623 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 678 Fredegundis (A909 BQ)
678
Proper motion: 0.681 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 120 Lachesis (A872 GB)
120
Proper motion: 0.323 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 639 Latona (A907 OA)
639
Proper motion: 0.394 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 123 Brunhild (A872 OB)
123
Proper motion: 0.435 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 135 Hertha (A874 DA)
135
Proper motion: 0.379 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 122 Gerda (A872 OA)
122
Proper motion: 0.389 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 127 Johanna (A872 VB)
127
Proper motion: 0.527 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 509 Iolanda (A903 HD)
509
Proper motion: 0.529 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 595 Polyxena (A906 FL)
595
Proper motion: 0.512 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 21 Lutetia (A852 VA)
21
Proper motion: 0.570 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 93 Minerva (A867 QA)
93
Proper motion: 0.564 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 119 Althaea (A872 GA)
119
Proper motion: 0.584 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 132 Aethra (A873 LA)
132
Proper motion: 0.855 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 139 Juewa (A874 TA)
139
Proper motion: 0.579 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 241 Germania (A884 RA)
241
Proper motion: 0.537 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 409 Aspasia (A895 XC)
409
Proper motion: 0.634 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 154 Bertha (A875 VD)
154
Proper motion: 0.559 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 90 Antiope (A866 TA)
90
Proper motion: 0.522 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 144 Vibilia (A875 LA)
144
Proper motion: 0.601 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 895 Helio (A918 NA)
895
Proper motion: 0.685 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 363 Padua (A893 FD)
363
Proper motion: 0.589 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 481 Emita (A902 CB)
481
Proper motion: 0.627 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 182 Elsa (A878 CC)
182
Proper motion: 0.594 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 24 Themis (A853 GA)
24
Proper motion: 0.519 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 70 Panopaea (A861 JA)
70
Proper motion: 0.640 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 503 Evelyn (A903 BL)
503
Proper motion: 0.596 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 65 Cybele (A861 EB)
65
Proper motion: 0.462 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 113 Amalthea (A871 EA)
113
Proper motion: 0.647 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 346 Hermentaria (A892 WC)
346
Proper motion: 0.593 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 306 Unitas (A891 EA)
306
Proper motion: 0.659 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 358 Apollonia (A893 EC)
358
Proper motion: 0.552 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 95 Arethusa (A867 WA)
95
Proper motion: 0.599 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 347 Pariana (A892 WD)
347
Proper motion: 0.647 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 758 Mancunia (A912 KB)
758
Proper motion: 0.524 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 480 Hansa (A901 KB)
480
Proper motion: 0.753 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 317 Roxane (A891 RD)
317
Proper motion: 0.673 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 160 Una (A876 DA)
160
Proper motion: 0.581 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 498 Tokio (A902 XA)
498
Proper motion: 0.648 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 389 Industria (A894 EE)
389
Proper motion: 0.620 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 159 Aemilia (A876 BA)
159
Proper motion: 0.531 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 704 Interamnia (A910 TC)
704
Proper motion: 0.615 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 37 Fides (A855 TB)
37
Proper motion: 0.574 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 488 Kreusa (A902 MC)
488
Proper motion: 0.550 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 776 Berbericia (A914 BE)
776
Proper motion: 0.668 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 4 Vesta (A807 FA)
4
Proper motion: 0.639 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 9 Metis (A848 HA)
9
Proper motion: 0.618 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 48 Doris (A857 SA)
48
Proper motion: 0.477 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 5 Astraea (A845 XA)
5
Proper motion: 0.493 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>
row['Full name'] : 92 Undina (A867 NA)
92
Proper motion: 0.371 arcmin / h
type(eph):  <class 'astropy.table.table.Table'>

저장

In [27]:
eph = MPC.get_ephemeris('A894 VC', start='1996-03-01', step='1h', number=30 * 24)
print(eph['Proper motion'].quantity.to('deg/h').max())
eph = MPC.get_ephemeris('A894 VC', location='P64',
                        ra_format={'sep': ':', 'unit': 'hourangle', 'precision': 1},
                        dec_format={'sep': ':', 'precision': 0},
                        step='1h')
print(eph)

0.023877777777777776 deg / h
          Date              RA       Dec    ... Uncertainty 3sig Unc. P.A.
                        hourangle    deg    ...      arcsec         deg
----------------------- ---------- -------- ... ---------------- ---------
2023-11-13 11:00:00.000 20:46:22.9 -5:18:33 ...                0      77.0
2023-11-13 12:00:00.000 20:46:28.0 -5:18:33 ...                0      76.9
2023-11-13 13:00:00.000 20:46:33.0 -5:18:33 ...                0      76.9
2023-11-13 14:00:00.000 20:46:38.1 -5:18:33 ...                0      77.0
2023-11-13 15:00:00.000 20:46:43.1 -5:18:33 ...                0      76.9
2023-11-13 16:00:00.000 20:46:48.2 -5:18:33 ...                0      77.0
2023-11-13 17:00:00.000 20:46:53.3 -5:18:33 ...                0      76.9
2023-11-13 18:00:00.000 20:46:58.5 -5:18:33 ...                0      77.0
2023-11-13 19:00:00.000 20:47:03.6 -5:18:33 ...                0      77.0
2023-11-13 20:00:00.000 20:47:08.8 -5:18:33 ...                0      77.0
                    ...        ...      ... ...              ...       ...
2023-11-15 02:00:00.000 20:49:41.8 -5:18:26 ...                0      76.9
2023-11-15 03:00:00.000 20:49:46.9 -5:18:26 ...                0      77.0
2023-11-15 04:00:00.000 20:49:52.0 -5:18:25 ...                0      77.0
2023-11-15 05:00:00.000 20:49:57.1 -5:18:25 ...                0      76.9
2023-11-15 06:00:00.000 20:50:02.1 -5:18:24 ...                0      76.9
2023-11-15 07:00:00.000 20:50:07.2 -5:18:24 ...                0      76.9
2023-11-15 08:00:00.000 20:50:12.2 -5:18:23 ...                0      77.0
2023-11-15 09:00:00.000 20:50:17.3 -5:18:22 ...                0      76.9
2023-11-15 10:00:00.000 20:50:22.3 -5:18:22 ...                0      77.0
2023-11-15 11:00:00.000 20:50:27.3 -5:18:21 ...                0      76.9
Length = 49 rows